Repository openPMD/openPMD-api, pull requests merged in 2018-07, with the labels that each got.

#284 Python: Particle Record Components
  CHANGELOG.rst
  include/openPMD/backend/BaseRecordComponent.hpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/Container.cpp
  src/binding/python/Record.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: Python3

#288 Version: 0.3.1-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#289 Post 0.3.1-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#291 C++ code checks and metrics in TravisCI
  .clang-tidy
  .travis.yml
  README.md
Labels: continuous integration, tests, third party, tools

#294 README: openPMD data
  README.md
Labels: documentation

#292 Whitespace Fixes
  .travis.yml
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS2FilePosition.hpp
  include/openPMD/IO/AbstractFilePosition.hpp
  test/AuxiliaryTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: refactoring

#293 Refactor: override implies virtual
  .travis.yml
  CHANGELOG.rst
  docs/source/dev/backend.rst
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/Record.hpp
  include/openPMD/backend/BaseRecord.hpp
Labels: refactoring

#296 Remove remaining redundant virtual specs
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
Labels: refactoring
