Repository openPMD/openPMD-api, pull requests merged in 2018-02, with the labels that each got.

#39 Readme: More Details
  CMakeLists.txt
  README.md
Labels: documentation

#41 Constants: Suffixes
  test/SerialIOTest.cpp
Labels: tests, warning

#40 Series: Add 1.1.0 Standard
  src/Series.cpp
Labels: refactoring

#42 Examples: 1.1.0
  test/SerialIOTest.cpp
Labels: bug, tests

#43 Examples 1.1.0: Update numParticles
  test/SerialIOTest.cpp
Labels: bug, tests

#45 MPI Info: Default to NULL
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
Labels: MPI, bug

#46 Unused Warnings
  include/backend/GenericPatchData.hpp
  test/CoreTest.cpp
Labels: tests, warning

#49 Badge: openPMD Standard
  README.md
Labels: documentation

#51 Warnings: Unused in Release
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
Labels: backend: HDF5, warning

#52 Iteration: Add Missing template spec.
  src/Iteration.cpp
Labels: bug

#54 Sphinx: Get Docs Started
  .readthedocs.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/dev/backend.rst
  docs/source/dev/buildoptions.rst
  docs/source/dev/contributing.rst
  docs/source/dev/dependencies.rst
  docs/source/dev/doxygen.rst
  docs/source/dev/doxyindex.rst
  docs/source/dev/repostructure.rst
  docs/source/dev/sphinx.rst
  docs/source/index.rst
  docs/source/install/changelog.rst
  docs/source/install/cmake.svg
  docs/source/install/conda.rst
  docs/source/install/conda.svg
  docs/source/install/general.rst
  docs/source/install/install.rst
  docs/source/install/manual.rst
  docs/source/install/spack.rst
  docs/source/install/spack.svg
  docs/source/openPMD.png
  docs/source/usage/advanced.rst
  docs/source/usage/firststeps.rst
  docs/source/usage/parallel.rst
  docs/source/usage/serial-reader.cpp
  docs/source/usage/serial-writer.cpp
  docs/source/usage/serial.rst
Labels: documentation

#55 Single header for all user-exposure.
  README.md
  include/openPMD.hpp
Labels: frontend: C++11, refactoring

#58 Mesh: Add Missing template spec.
  src/Mesh.cpp
  src/backend/MeshRecordComponent.cpp
Labels: bug

#60 Update CMake
  CMakeLists.txt
Labels: install, refactoring

#56 Verify h5py compliant bool.
  src/IO/HDF5/HDF5IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: HDF5, tests

#57 Comply with 1.0.1 and 1.1.0.
  .travis/download_samples.sh
  include/Series.hpp
  include/backend/Attributable.hpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: frontend: C++11, tests

#64 CMake: Install Sub-Paths
  CMakeLists.txt
Labels: install, refactoring

#66 Travis: Build Stages
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
  docs/source/conf.py
Labels: tests, third party

#68 Docs: ADIOS 2.1+
  CMakeLists.txt
  README.md
  docs/source/dev/dependencies.rst
Labels: documentation

#69 Fix Includes
  include/Dataset.hpp
  include/IO/AbstractIOHandler.hpp
  include/IO/AccessType.hpp
  include/IO/IOTask.hpp
  include/Mesh.hpp
  include/ParticlePatches.hpp
  include/ParticleSpecies.hpp
  include/Record.hpp
  include/RecordComponent.hpp
  include/Series.hpp
  include/auxiliary/Memory.hpp
  include/auxiliary/StringManip.hpp
  include/auxiliary/Variadic.hpp
  include/backend/Attributable.hpp
  include/backend/Attribute.hpp
  include/backend/BaseRecord.hpp
  include/backend/BaseRecordComponent.hpp
  include/backend/Container.hpp
  include/backend/GenericPatchData.hpp
  include/backend/MeshRecordComponent.hpp
  include/backend/PatchPosition.hpp
  include/backend/PatchRecord.hpp
  include/backend/PatchRecordComponent.hpp
  include/backend/Writable.hpp
Labels: bug

#72 CMake: Single lib
  CMakeLists.txt
Labels: install, refactoring

#71 example: remove unused variable
  examples/1_structure.cpp
Labels: warning

#74 MPark.Variant
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  include/IO/IOTask.hpp
  include/auxiliary/Variadic.hpp
  include/backend/GenericPatchData.hpp
  include/mpark_variant/variant.hpp
  src/backend/GenericPatchData.cpp
  src/backend/PatchRecord.cpp
  test/AuxiliaryTest.cpp
Labels: discussion, install, refactoring

#73 Add introductory serial & parallel read & write examples
  CMakeLists.txt
  README.md
  docs/source/usage/2_read_serial.cpp
  docs/source/usage/3_write_serial.cpp
  docs/source/usage/4_read_parallel.cpp
  docs/source/usage/5_write_parallel.cpp
  docs/source/usage/parallel.rst
  docs/source/usage/serial-reader.cpp
  docs/source/usage/serial-writer.cpp
  docs/source/usage/serial.rst
  examples/1_structure.cpp
  examples/2_read_serial.cpp
  examples/3_write_serial.cpp
  examples/4_read_parallel.cpp
  examples/5_write_parallel.cpp
  examples/6_dump_filebased_series.cpp
  examples/7_extended_write_serial.cpp
  include/auxiliary/Memory.hpp
  include/backend/GenericPatchData.hpp
Labels: documentation

#75 Doxygen: Mainpage
  README.md
  docs/Doxyfile
Labels: documentation

#76 Examples: Cleanup
  .gitignore
  CMakeLists.txt
  README.md
  docs/Makefile
  docs/source/dev/buildoptions.rst
  docs/source/usage/parallel.rst
  docs/source/usage/serial.rst
  examples/1_structure.cpp
  examples/2_read_serial.cpp
  examples/3_write_serial.cpp
  examples/4_read_parallel.cpp
  examples/5_write_parallel.cpp
  examples/6_dump_filebased_series.cpp
  examples/7_extended_write_serial.cpp
Labels: documentation

#77 MPark.Variant: Fix Include Dir
  include/auxiliary/Variadic.hpp
  include/mpark/variant.hpp
Labels: bug, third party

#81 auxiliary:: namespace
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/auxiliary/StringManip.hpp
  include/openPMD/auxiliary/Variadic.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/backend/GenericPatchData.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/PatchRecord.cpp
  test/AuxiliaryTest.cpp
Labels: internal, refactoring

#88 Contributing Guidelines
  CONTRIBUTING.rst
  docs/source/usage/firststeps.rst
Labels: documentation

#89 Container: Add Missing Methods
  include/openPMD/backend/Container.hpp
Labels: refactoring

#90 Travis: CMake Binary Download
  .travis.yml
  .travis/spack/packages.yaml
Labels: refactoring, tests, third party
