Repository openPMD/openPMD-api, pull requests merged in 2018-04, with the labels that each got.

#109 Third Party Installs
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  docs/source/install/install.rst
  share/openPMD/thirdParty/variant/include/mpark/variant.hpp
Labels: install, third party

#111 Travis: Modules On Missing Cache Broken
  .travis.yml
Labels: install, tests, third party

#112 MPark.Variant: link as System
  CMakeLists.txt
Labels: third party, warning

#110 Replace Boost.Test with Catch2
  .travis.yml
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/catch2/include/catch/catch.hpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: install, tests, third party

#114 Wpessimizing-move on return
  include/openPMD/auxiliary/Memory.hpp
Labels: warning

#115 Travis: OSX
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: machine/system, tests, third party

#118 [WIP] Fix ParallelIOTest
  CMakeLists.txt
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: MPI, backend: HDF5, bug

#119 C++11: Target Compile Property
  CMakeLists.txt
Labels: install

#120 Docs: More Links Dependencies
  README.md
  docs/source/dev/dependencies.rst
Labels: documentation, third party

#121 CMake: Std C++11 Only
  CMakeLists.txt
Labels: install

#116 [WIP] HowTo on creating a backend
  CMakeLists.txt
  docs/source/dev/backend.rst
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Series.hpp
  src/IO/AbstractIOHandler.cpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/IOTask.cpp
  src/Series.cpp
  test/CoreTest.cpp
Labels: backend, backend: HDF5, documentation

#123 Rename Variadic to Variant
  include/openPMD/IO/IOTask.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/backend/GenericPatchData.hpp
  test/AuxiliaryTest.cpp
Labels: cosmetic, internal, refactoring

#124 Handle noHDF5+MPI gracefully
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  src/IO/AbstractIOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
Labels: MPI, backend, backend: HDF5

#128 Doxygen: Python Highlighting
  README.md
Labels: documentation

#129 Doxygen: Exclude Thirdparties
  docs/Doxyfile
Labels: documentation

#133 README: Updates
  README.md
Labels: documentation

#132 Spack Package
  README.md
  docs/source/install/install.rst
Labels: install, third party

#136 Python: Containers & MeshRecordComponent
  CMakeLists.txt
  examples/2_read_serial.py
  src/binding/python/AccessType.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/Container.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/IterationEncoding.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/openPMD.cpp
Labels: frontend: Python 3

#142 Write Example: Simplify
  examples/3_write_serial.cpp
Labels: documentation, refactoring

#146 Rewrite ParticlePatches
  CMakeLists.txt
  examples/7_extended_write_serial.cpp
  include/openPMD/ParticlePatches.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/GenericPatchData.hpp
  include/openPMD/backend/PatchPosition.hpp
  include/openPMD/backend/PatchRecord.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/RecordComponent.cpp
  src/backend/GenericPatchData.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: api change, frontend: C++11, frontend: Python 3, refactoring

#126 ADIOS1 backend
  CMakeLists.txt
  README.md
  cmake/FindADIOS.cmake
  docs/source/dev/backend.rst
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS1FilePosition.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/auxiliary/StringManip.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/Series.cpp
  test/AuxiliaryTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: MPI, backend: ADIOS1
