Repository openPMD/openPMD-api, pull requests merged in 2018-03, with the labels that each got.

#59 Python Bindings: Initial Structure
  .travis.yml
  .travis/spack/packages.yaml
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  docs/source/install/install.rst
  docs/source/usage/2_read_serial.py
  docs/source/usage/serial.rst
  examples/2_read_serial.py
  include/openPMD/ParticlePatches.hpp
  include/openPMD/RecordComponent.hpp
  src/RecordComponent.cpp
  src/binding/python/AccessType.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/IterationEncoding.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/openPMD.cpp
Labels: frontend: Python 3

#92 Travis: Skip Spack Bootstrap
  .travis.yml
Labels: refactoring, tests, third party

#93 Travis: Bump Boost to 1.65.0
  .travis.yml
Labels: tests, third party

#97 CMake: Print External MPark.Variant
  CMakeLists.txt
Labels: documentation, install

#96 Travis: GCC 7.2.0
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: tests, third party

#94 fix type conflict between Extent and std::vector< size_t >
  include/openPMD/Dataset.hpp
  src/Dataset.cpp
Labels: bug

#100 CMake: Space too much
  CMakeLists.txt
Labels: documentation, install

#102 Add missing override
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/Record.hpp
  include/openPMD/backend/BaseRecord.hpp
Labels: warning

#103 Feature Defines: 0(False) or 1(True)
  CMakeLists.txt
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
  test/SerialIOTest.cpp
Labels: MPI, backend: ADIOS1, backend: HDF5, warning

#104 Add override to virtual destructors
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
Labels: backend: ADIOS1, backend: HDF5, warning

#105 Control Building Tests
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
Labels: install, tests

#106 Example Download: curl
  .travis/download_samples.sh
Labels: machine/system, tests

#107 Move overrides: ADIOS Backends
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
Labels: backend: ADIOS1, backend: ADIOS2, warning

#108 Fix: MPI but no HDF5
  src/IO/AbstractIOHandler.cpp
Labels: MPI, backend: HDF5, bug
