Repository openPMD/openPMD-api, pull requests merged in 2018-09, with the labels that each got.

#332 Attributable: virtual default destructor
  CHANGELOG.rst
  include/openPMD/backend/Attributable.hpp
Labels: warning

#334 Travis: Skip clang-tidy & IWYU
  .travis.yml
Labels: continuous integration

#337 Integer Type System: Refactor
  CHANGELOG.rst
  examples/7_extended_write_serial.cpp
  include/openPMD/Datatype.hpp
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/backend/Attribute.hpp
  src/Datatype.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  src/ParticlePatches.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/RecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, api: breaking, backend, bug, frontend: C++11, frontend: Python3, refactoring

#184 SerialTest: MSVC long double read
  test/SerialIOTest.cpp
Labels: bug, machine/system, tests

#341 setAttribute: Explicit C-String Handling
  CHANGELOG.rst
  include/openPMD/backend/Attributable.hpp
Labels: frontend: C++11, refactoring

#342 Tests: setAttribute with int/long
  test/SerialIOTest.cpp
Labels: tests

#344 SerialIO ADIOS1 Test: Bool
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS1, tests

#345 Attribute: Implement get<>() Cast
  CHANGELOG.rst
  include/openPMD/Datatype.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Attribute.hpp
  src/Datatype.cpp
  src/RecordComponent.cpp
  src/backend/Attributable.cpp
  test/SerialIOTest.cpp
Labels: refactoring

#330 set_attribute: broken numpy, list and string support
  .appveyor.yml
  .travis.yml
  CHANGELOG.rst
  docs/requirements.txt
  docs/source/dev/dependencies.rst
  src/binding/python/Attributable.cpp
  src/binding/python/openPMD.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, frontend: Python3

#347 Version: 0.5.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#350 Post 0.5.0-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#351 Numpy Dtype
  CHANGELOG.rst
  include/openPMD/binding/python/Numpy.hpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: api: breaking, frontend: Python3

#353 Refactor Numpy Stride Check
  CHANGELOG.rst
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
Labels: frontend: Python3, refactoring

#355 dataOrder: string
  CHANGELOG.rst
  src/Mesh.cpp
Labels: affects latest release, bug

#359 Examples: Close Handles
  CHANGELOG.rst
  examples/1_structure.cpp
  examples/2_read_serial.py
  examples/3_write_serial.py
  examples/6_dump_filebased_series.cpp
  examples/7_extended_write_serial.cpp
Labels: documentation, refactoring, tests

#352 Comply with constraints in IO documentation
  CHANGELOG.rst
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/MeshRecordComponent.cpp
Labels: backend, backend: ADIOS1, backend: HDF5, documentation, internal

#358 Fix and test constant scalar Records
  CHANGELOG.rst
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/Iteration.cpp
  src/ParticleSpecies.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, internal

#360 CPP Examples: Close Handles
  CHANGELOG.rst
  examples/2_read_serial.cpp
  examples/3_write_serial.cpp
Labels: documentation, refactoring, tests

#363 ParticlePatches: Idx Range Change
  CHANGELOG.rst
  include/openPMD/backend/PatchRecordComponent.hpp
Labels: affects latest release, bug, internal

#364 ParticlePatches: load() at once
  CHANGELOG.rst
  include/openPMD/backend/PatchRecordComponent.hpp
  test/SerialIOTest.cpp
Labels: api: breaking, frontend: C++11, tests

#365 Version: 0.6.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#366 Post 0.6.0-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#367 Use Catch2 2.3.0+
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/catch2/include/catch2/catch.hpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: tests, third party

#369 Python Stride Check: Too Strict
  CHANGELOG.rst
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
Labels: affects latest release, bug, frontend: Python3

#314 Python: Extended Write Example
  CHANGELOG.rst
  CMakeLists.txt
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
Labels: documentation, frontend: Python3, tests

#371 Post 0.6.1-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#372 Python: Relax Strides Further
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
Labels: affects latest release, bug, frontend: Python3

#373 Post 0.6.2-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation
