Repository openPMD/openPMD-api, pull requests merged in 2018-05, with the labels that each got.

#154 RTD Build Pygments
  docs/requirements.txt
  docs/source/usage/firststeps.rst
  docs/source/usage/serial.rst
Labels: documentation, third party

#157 Syntax Highlighting: Fix RTD Theme
  docs/requirements.txt
Labels: bug, documentation, third party

#158 Python: Container With Insert on Access
  src/binding/python/Container.cpp
Labels: frontend: Python3, refactoring

#161 Docstring Typo Double
  include/openPMD/Mesh.hpp
Labels: documentation

#162 Fix Warnings: Unused, Cast
  src/IO/AbstractIOHandlerImpl.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5, warning

#164 ADIOS filesystem: path shadowed by var
  src/IO/ADIOS/ADIOS1IOHandler.cpp
Labels: backend: ADIOS1, bug

#163 Files: Access Rights
  .travis.yml
  CMakeLists.txt
  COPYING
  COPYING.LESSER
  Dockerfile
  README.md
  include/openPMD/Dataset.hpp
  include/openPMD/Datatype.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractFilePosition.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AccessType.hpp
  include/openPMD/IO/Format.hpp
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  include/openPMD/IO/HDF5/HDF5FilePosition.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Record.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/StringManip.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/PatchRecord.hpp
  include/openPMD/backend/Writable.hpp
  src/Dataset.cpp
  src/Datatype.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/PatchRecord.cpp
  src/backend/Writable.cpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: refactoring

#166 ADIOS: Fix Unused Parameters
  src/IO/ADIOS/ADIOS1IOHandler.cpp
Labels: backend: ADIOS1, warning

#167 Warning in Float Literals
  test/CoreTest.cpp
Labels: warning

#168 Tests: Add Std Includes
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: bug, tests

#170 CMake: openPMD.py MSVC Name Conflict
  CMakeLists.txt
Labels: bug, install, tools

#159 Python: Serial Write Example
  CMakeLists.txt
  docs/source/usage/3_write_serial.py
  docs/source/usage/serial.rst
  examples/3_write_serial.py
Labels: documentation, frontend: Python3, tests

#169 Container Particle Species: Fix Overload
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  src/ParticleSpecies.cpp
Labels: backend, bug

#174 Writable: Fix Missing Include
  include/openPMD/backend/Writable.hpp
Labels: backend, bug

#176 Introduce switch for invasive tests
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  include/openPMD/backend/Writable.hpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: bug, install, machine/system, refactoring, tests

#177 Warnings: Class then Struct
  CMakeLists.txt
  include/openPMD/backend/Writable.hpp
  test/AuxiliaryTest.cpp
Labels: warning

#178 Python: Module.have_variant
  src/binding/python/openPMD.cpp
Labels: frontend: Python3

#172 Container: Read Only Throw Missing
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: frontend: C++11, frontend: Python3, refactoring, tests

#180 Module Feature Variants: As Map
  src/binding/python/openPMD.cpp
Labels: frontend: Python3

#182 MSVC: decltype function Work-Around
  include/openPMD/auxiliary/HasToString.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
Labels: bug, machine/system

#173 Windows Support and AppVeyor CI
  .appveyor.yml
  .travis/download_samples.ps1
  CMakeLists.txt
  README.md
  include/openPMD/auxiliary/HasToString.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  test/SerialIOTest.cpp
Labels: install, machine/system

#183 Key Error on Read-Only
  include/openPMD/auxiliary/OutOfRangeMsg.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
Labels: internal, refactoring

#188 Adjust Attribute Set Error Text
  include/openPMD/auxiliary/OutOfRangeMsg.hpp
  include/openPMD/backend/Attributable.hpp
Labels: internal, refactoring

#185 Extents: size_t to uint64_t
  include/openPMD/RecordComponent.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
Labels: internal, refactoring

#189 Add LGPLv3+ Headers
  include/openPMD/Dataset.hpp
  include/openPMD/Datatype.hpp
  include/openPMD/IO/ADIOS/ADIOS1FilePosition.hpp
  include/openPMD/IO/ADIOS/ADIOS2FilePosition.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractFilePosition.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AccessType.hpp
  include/openPMD/IO/Format.hpp
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  include/openPMD/IO/HDF5/HDF5FilePosition.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/IterationEncoding.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Record.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/auxiliary/OutOfRangeMsg.hpp
  include/openPMD/auxiliary/StringManip.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/MeshRecordComponent.hpp
  include/openPMD/backend/PatchRecord.hpp
  include/openPMD/backend/Writable.hpp
  src/Dataset.cpp
  src/Datatype.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/IterationEncoding.cpp
  src/Mesh.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/backend/Attributable.cpp
  src/backend/BaseRecordComponent.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/Writable.cpp
  src/binding/python/AccessType.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/IterationEncoding.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/openPMD.cpp
Labels: documentation

#191 Container: ipython completions
  src/binding/python/Container.cpp
Labels: frontend: Python3

#193 Fix standard consistency
  include/openPMD/backend/Writable.hpp
  src/Mesh.cpp
  src/Record.cpp
Labels: bug, internal, tests

#197 Windows: Test Python Import
  .appveyor.yml
  CMakeLists.txt
Labels: machine/system, tests

#198 Docs: Typo Shared
  docs/source/dev/buildoptions.rst
Labels: documentation, install

#199 CMake: ADIOS1 Static Lib Suffix
  cmake/FindADIOS.cmake
Labels: cosmetic, install

#201 README: Typo Namespace
  README.md
Labels: bug, documentation

#202 Readme: Spack Badge
  README.md
Labels: documentation, install

#200 Docs: All Static Builds
  docs/source/dev/buildoptions.rst
Labels: documentation, install

#206 Docs: Fix CMake Static ADIOS
  docs/source/dev/buildoptions.rst
Labels: bug, documentation

#204 Helper: Raw Pointer store/load
  examples/2_read_serial.cpp
  examples/3_write_serial.cpp
  examples/4_read_parallel.cpp
  examples/5_write_parallel.cpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/auxiliary/ShareRaw.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  include/openPMD/openPMD.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: api change, frontend: C++11, refactoring

#215 CI: Test HDF5 Minimal Version
  .travis.yml
Labels: backend: HDF5, tests, third party

#207 Replace boost.filesystem
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  examples/7_extended_write_serial.cpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/auxiliary/Filesystem.hpp
  include/openPMD/auxiliary/StringManip.hpp
  openPMDConfig.cmake.in
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/Series.cpp
  src/auxiliary/Filesystem.cpp
  test/AuxiliaryTest.cpp
Labels: Boost, backend, internal, refactoring, third party
