Repository openPMD/openPMD-api, pull requests merged in 2018-06, with the labels that each got.

#220 Singularity Container
  Singularity
Labels: continuous deployment

#218 Compiler Docs: VS 2015
  README.md
  docs/source/dev/dependencies.rst
Labels: documentation

#221 Singularity Container: Update
  Singularity
Labels: continuous deployment

#224 GCC 4.8: <regex> to <regex.h>
  src/Series.cpp
Labels: internal, machine/system, refactoring

#222 Readme: Frontend Text
  README.md
  docs/source/index.rst
Labels: documentation

#223 CMake Config: Support NOMPI, Install ADIOS Module
  CMakeLists.txt
  README.md
  openPMDConfig.cmake.in
Labels: bug, install

#226 Version: 0.1.0-alpha
  CHANGELOG.rst
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#227 SerialIOTest: loadChunk template ADIOS1
  CHANGELOG.rst
  test/SerialIOTest.cpp
Labels: affects latest release, bug, tests

#230 Add RODARE Meta Information
  .rodare.json
Labels: documentation, third party

#228 Serial ADIOS: Refactor MPI Comm
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS1, refactoring

#212 Minimize number of flushes in backend
  CHANGELOG.rst
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend, internal, refactoring

#231 Version: 0.1.1-alpha
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#232 Add DOI
  README.md
Labels: documentation

#233 Conda: Conda-Forge Package
  README.md
  docs/source/install/install.rst
Labels: documentation, install, third party

#234 Changelog: Prepare 0.1.2-alpha
  .rodare.json
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#235 New Title In README
  .rodare.json
  README.md
Labels: documentation

#237 CMake: Overwritable Install Paths
  CHANGELOG.rst
  CMakeLists.txt
Labels: bug, install

#236 Singularity: ADIOS
  Singularity
  cmake/FindADIOS.cmake
Labels: continuous deployment, third party

#238 CMake: Examples Option and Move FindADIOS
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  share/openPMD/cmake/FindADIOS.cmake
Labels: tests

#239 RODARE: More Meta Info
  .rodare.json
Labels: documentation

#219 First Python Numpy Bindings
  .appveyor.yml
  CHANGELOG.rst
  examples/2_read_serial.py
  examples/3_write_serial.py
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
Labels: api: new, frontend: Python3

#241 CMake: More Control on Build Dirs
  CHANGELOG.rst
  CMakeLists.txt
Labels: install, refactoring

#242 Version: 0.2.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#243 Post 0.2.0-alpha Changelog Tpl
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#245 Docs: Updates
  README.md
  docs/source/dev/dependencies.rst
  docs/source/dev/repostructure.rst
  docs/source/index.rst
Labels: documentation

#250 Travis HDF5: 1.10.1
  .travis/spack/packages.yaml
Labels: MPI, backend: HDF5, bug, continuous integration

#247 Check validity of internally used pointers
  include/openPMD/RecordComponent.hpp
  test/CoreTest.cpp
Labels: internal, tests

#246 Travis: GCC Updates
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: continuous integration

#251 Docs: MPI Version
  README.md
  docs/source/dev/dependencies.rst
Labels: documentation, third party

#210 CI: GCC 4.8
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
  CMakeLists.txt
Labels: continuous integration

#256 Python: Attribute Keys
  README.md
  src/binding/python/Container.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/ParticleSpecies.cpp
Labels: api: new, frontend: Python3

#257 Write Examples: Scalar Record Name
  examples/3_write_serial.cpp
  examples/3_write_serial.py
Labels: refactoring, tests

#229 Replace ASSERT with VERIFY
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/backend.rst
  docs/source/dev/buildoptions.rst
  examples/7_extended_write_serial.cpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/Filesystem.hpp
  include/openPMD/backend/Attributable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/Series.cpp
  src/auxiliary/Filesystem.cpp
Labels: internal, refactoring

#259 Docs: http & serial intro
  README.md
  docs/source/usage/serial.rst
Labels: documentation

#258 Remove MPI from serial ADIOS interface
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  test/SerialIOTest.cpp
Labels: MPI, backend: ADIOS1, internal, refactoring

#260 ADIOS1: VERIFY
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
Labels: MPI, backend: ADIOS1, bug

#262 SerialIOTest: Shadow Warning
  test/SerialIOTest.cpp
Labels: tests, warning

#267 Fix ADIOS Warnings
  include/openPMD/IO/AbstractIOHandler.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
Labels: backend: ADIOS1, warning

#268 setAttribute: const&
  CHANGELOG.rst
  include/openPMD/backend/Attributable.hpp
Labels: api: breaking, frontend: C++11

#190 Travis-CI: ADIOS1 Tests
  .travis.yml
  .travis/spack/packages.yaml
Labels: backend: ADIOS1, continuous integration, tests

#266 Python: Expose Attributes Fully
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  examples/2_read_serial.py
  examples/3_write_serial.py
  src/binding/python/AccessType.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/Container.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/IterationEncoding.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/openPMD.cpp
Labels: api: new, frontend: Python3

#269 Fix ADIOS1 String Attributes
  .travis.yml
  CHANGELOG.rst
  src/IO/ADIOS/ADIOS1IOHandler.cpp
Labels: affects latest release, backend: ADIOS1, bug, tests

#272 Version: 0.3.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#273 Post 0.3.0-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#274 Install Docs: Improve from Source
  CHANGELOG.rst
  README.md
  docs/source/install/install.rst
Labels: affects latest release, bug, documentation, install

#277 CMake: Add openPMD::openPMD ALIAS
  CHANGELOG.rst
  CMakeLists.txt
  README.md
Labels: install

#278 Spack: Python3
  CHANGELOG.rst
  README.md
  docs/source/install/install.rst
Labels: documentation, frontend: Python3, install

#281 Ship pybind11 v2.2.3
  .appveyor.yml
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/pybind11/CMakeLists.txt
  share/openPMD/thirdParty/pybind11/CONTRIBUTING.md
  share/openPMD/thirdParty/pybind11/LICENSE
  share/openPMD/thirdParty/pybind11/MANIFEST.in
  share/openPMD/thirdParty/pybind11/README.md
  share/openPMD/thirdParty/pybind11/include/pybind11/attr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/buffer_info.h
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/chrono.h
  share/openPMD/thirdParty/pybind11/include/pybind11/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/complex.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/descr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/init.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/typeid.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen.h
  share/openPMD/thirdParty/pybind11/include/pybind11/embed.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eval.h
  share/openPMD/thirdParty/pybind11/include/pybind11/functional.h
  share/openPMD/thirdParty/pybind11/include/pybind11/iostream.h
  share/openPMD/thirdParty/pybind11/include/pybind11/numpy.h
  share/openPMD/thirdParty/pybind11/include/pybind11/operators.h
  share/openPMD/thirdParty/pybind11/include/pybind11/options.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/pybind11/__init__.py
  share/openPMD/thirdParty/pybind11/pybind11/__main__.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/tools/FindCatch.cmake
  share/openPMD/thirdParty/pybind11/tools/FindEigen3.cmake
  share/openPMD/thirdParty/pybind11/tools/FindPythonLibsNew.cmake
  share/openPMD/thirdParty/pybind11/tools/check-style.sh
  share/openPMD/thirdParty/pybind11/tools/libsize.py
  share/openPMD/thirdParty/pybind11/tools/mkdoc.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Config.cmake.in
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: frontend: Python3, install, third party

#249 unittests for python API
  .gitignore
  CMakeLists.txt
  test/python/unittest/API/APITest.py
  test/python/unittest/API/__init__.py
  test/python/unittest/Test.py
  test/python/unittest/TestUtilities/TestUtilities.py
  test/python/unittest/TestUtilities/__init__.py
  test/python/unittest/__init__.py
Labels: continuous integration, frontend: Python3, tests

#282 Make Container constructor protected
  CHANGELOG.rst
  include/openPMD/backend/Container.hpp
  src/binding/python/Container.cpp
  test/AuxiliaryTest.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, api: breaking, frontend: C++11, frontend: Python3, internal

#285 Minor fix to README source compilation process
  README.md
  docs/source/install/install.rst
Labels: bug, documentation, install

#286 Python Load Data
  CHANGELOG.rst
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, frontend: Python3
