Repository openPMD/openPMD-api, pull requests merged in 2018-08, with the labels that each got.

#298 Spack: load -r
  .appveyor.yml
  CHANGELOG.rst
  README.md
  docs/source/install/install.rst
Labels: documentation, install

#299 Travis-CI: OSX Update
  .travis.yml
Labels: tests, third party

#302 Fix ADIOS2 File Position Include
  include/openPMD/IO/ADIOS/ADIOS2FilePosition.hpp
Labels: affects latest release, backend: ADIOS2, bug

#301 Travis: OSX High Sierra
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: third party

#303 Travis: Fix Overlapping Caches
  .travis.yml
Labels: continuous integration

#305 Path Arguments: Pass-by-Value
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
Labels: api: breaking, frontend: C++11, refactoring

#308 Travis: Descriptive Job Names
  .travis.yml
Labels: continuous integration

#304 Default Constructors/Destructors
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/backend/PatchRecord.cpp
  src/backend/Writable.cpp
Labels: backend, refactoring

#300 IWYU: Public Headers
  examples/2_read_serial.cpp
  examples/3_write_serial.cpp
  examples/4_read_parallel.cpp
  include/openPMD/ParticlePatches.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/openPMD.hpp
  src/Dataset.cpp
  test/CoreTest.cpp
Labels: api: breaking, frontend: C++11, refactoring

#297 Fail fast during flush of empty Records
  CHANGELOG.rst
  CMakeLists.txt
  examples/1_structure.cpp
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Record.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/PatchRecord.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/Mesh.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, api: breaking, backend, internal

#311 Fix #310: Name sanitization in the ADIOS backend
  CHANGELOG.rst
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: affects latest release, backend: ADIOS1, backend: HDF5, bug, internal

#309 Handle zero-extent dataset creation and dataset write
  src/RecordComponent.cpp
  src/backend/PatchRecordComponent.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
Labels: api: breaking, internal, refactoring

#313 Version: 0.4.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
Labels: documentation

#315 Post 0.4.0-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
Labels: documentation

#316 Issue template: question
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#318 Numpy: float is double
  CHANGELOG.rst
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
Labels: affects latest release, api: breaking, bug, frontend: Python3

#319 Python: Dataset Method Namings
  CHANGELOG.rst
  src/binding/python/Dataset.cpp
Labels: affects latest release, api: breaking, bug, frontend: Python3

#320 Numpy: but C float is single
  CHANGELOG.rst
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
Labels: frontend: Python3, refactoring

#323 Invasive Tests: Only CI
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: continuous integration, refactoring, tests

#324 Invasive Tests: Avoid Side Effects
  CHANGELOG.rst
  include/openPMD/RecordComponent.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  include/openPMD/backend/Writable.hpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: refactoring, tests

#325 Error Type: Remove const char signature
  CHANGELOG.rst
  include/openPMD/IO/AbstractIOHandler.hpp
Labels: backend, refactoring

#326 Dataset: Fix setCompression Detection
  CHANGELOG.rst
  src/Dataset.cpp
  test/SerialIOTest.cpp
Labels: bug

#327 Attribute Error: Remove const char signature
  CHANGELOG.rst
  include/openPMD/backend/Attributable.hpp
Labels: backend, refactoring
