Repository openPMD/openPMD-api, pull requests merged in 2019-01, with the labels that each got.

#405 Clarify instructions for installing from source
  docs/source/install/install.rst
Labels: documentation

#409 SerialIOTest: Use After Free in Patches
  CHANGELOG.rst
  test/SerialIOTest.cpp
Labels: affects latest release, bug, tests

#408 load_chunk order of arguments
  CHANGELOG.rst
  NEWS.rst
  examples/2_read_serial.cpp
  examples/2_read_serial.py
  include/openPMD/RecordComponent.hpp
  src/binding/python/RecordComponent.cpp
  test/CoreTest.cpp
Labels: api: breaking, frontend: C++11, frontend: Python3, refactoring

#411 Benchmark: Slicer & Filler Destructors
  CHANGELOG.rst
  include/openPMD/benchmark/mpi/BlockSlicer.hpp
  include/openPMD/benchmark/mpi/DatasetFiller.hpp
Labels: bug, tests

#412 Travis-CI: Clang 7
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
  examples/8_benchmark_parallel.cpp
  src/binding/python/Container.cpp
Labels: continuous integration, warning

#416 RecordComponent: storeChunk Use-after-Free
  .travis.yml
  CHANGELOG.rst
  include/openPMD/RecordComponent.hpp
Labels: bug, frontend: C++11

#417 Add Coverity Scan
  .travis.yml
  README.md
Labels: continuous integration

#419 MPI Parallel mkdir
  CHANGELOG.rst
  src/auxiliary/Filesystem.cpp
Labels: MPI, affects latest release, bug

#420 IOTask: Parameter Member Init
  CHANGELOG.rst
  include/openPMD/IO/IOTask.hpp
Labels: refactoring

#421 Parallel ADIOS1: Heap-Use-After Free
  CHANGELOG.rst
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
Labels: MPI, affects latest release, backend: ADIOS1, bug

#422 ParallelIOTest: Fix Delete Mismatch
  CHANGELOG.rst
  test/ParallelIOTest.cpp
Labels: MPI, affects latest release, tests

#410 IOTask: AbstractParameter Slice Safety
  CHANGELOG.rst
  include/openPMD/IO/IOTask.hpp
Labels: machine/system, refactoring

#423 CI: Minimal Clang-Tidy
  .clang-tidy
  .travis.yml
  CHANGELOG.rst
Labels: continuous integration

#424 gitignore: KDevelop
  .gitignore
  CHANGELOG.rst
Labels: tools

#425 Mesh: attribute setters const ref
  CHANGELOG.rst
  include/openPMD/Mesh.hpp
  src/Mesh.cpp
Labels: frontend: C++11, refactoring

#426 Readme typo: shared
  README.md
Labels: documentation, install

#427 BaseRecord: Shared Linking on OSX
  CHANGELOG.rst
  src/Record.cpp
Labels: affects latest release, bug, machine/system

#431 Travis: Homebrew 1.9.0
  .travis.yml
Labels: bug, continuous integration, machine/system, third party

#430 Docs: Particle Writing Python
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/index.rst
  docs/source/usage/examples.rst
  examples/9_particle_write_serial.py
Labels: documentation

#429 JSON Backend: Avoid Tmp Copies
  CHANGELOG.rst
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
Labels: backend: JSON, refactoring

#433 Contributors: Ray Donnelly
  .rodare.json
Labels: continuous deployment, documentation

#432 Version: 0.7.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: api: breaking, documentation

#434 Post 0.7.0-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#438 pybind11: C++17 variant trait
  CHANGELOG.rst
  src/binding/python/Attributable.cpp
Labels: affects latest release, bug, frontend: Python3, install

#439 Doc: Release Doxygen & RTD
  CHANGELOG.rst
  docs/source/dev/release.rst
Labels: documentation

#440 Doc: ADIOS1 Backend
  CHANGELOG.rst
  docs/source/backends/adios1.rst
  docs/source/backends/json.rst
  docs/source/index.rst
Labels: backend: ADIOS1, documentation

#441 Travis CI: OSX with libc++
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: continuous integration, machine/system

#442 IOTask Parameters: Export Symbols
  CHANGELOG.rst
  include/openPMD/IO/IOTask.hpp
Labels: affects latest release, backend: ADIOS1, bug, machine/system

#444 Travis CI: Clang with libc++
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
Labels: continuous integration, machine/system

#445 Doc: Spack Variant Updates
  CHANGELOG.rst
  README.md
  docs/source/install/install.rst
Labels: documentation, install, third party

#447 Version: 0.7.1-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: backend: ADIOS1, bug, install, machine/system

#448 Post 0.7.1-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#450 Doc: PyPI
  README.md
  docs/source/install/install.rst
  docs/source/install/pypi.svg
Labels: continuous deployment, documentation, install

#449 Doc: MPI
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/usage/parallel.rst
Labels: MPI, documentation

#451 Doc: PyPI Shield
  README.md
Labels: continuous deployment, documentation, install
