Repository openPMD/openPMD-api, pull requests merged in 2019-02, with the labels that each got.

#435 Remove All Python 2.7 Traces
  .travis.yml
  .travis/spack/packages.yaml
  CMakeLists.txt
  test/python/unittest/API/APITest.py
Labels: continuous integration, frontend: Python3, refactoring, tests

#457 Homebew: no --cleanup
  .travis.yml
Labels: continuous integration

#460 Differentiate accessTypes on use
  .travis.yml
  CHANGELOG.rst
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
Labels: affects latest release, backend, bug, internal, refactoring

#391 CMake 3.12.4+: _ROOT Vars
  CHANGELOG.rst
  CMakeLists.txt
Labels: install, warning

#464 CMake: Find Package _ROOT Env Policy
  CHANGELOG.rst
  openPMDConfig.cmake.in
Labels: install, warning

#465 MPark.Variant: 1.4.0+
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/variant/include/mpark/variant.hpp
Labels: internal, third party

#466 Catch2: 2.6.1+
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/catch2/include/catch2/catch.hpp
Labels: tests, third party

#468 Spack CMake on CI: Move Install
  .travis.yml
Labels: continuous integration, third party

#467 NLohmann-JSON: 3.5.0+
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/json/CMakeLists.txt
  share/openPMD/thirdParty/json/LICENSE.MIT
  share/openPMD/thirdParty/json/cmake/config.cmake.in
  share/openPMD/thirdParty/json/single_include/nlohmann/json.hpp
Labels: backend: JSON, third party

#469 Record Component: Fix Range Checks
  CHANGELOG.rst
  include/openPMD/RecordComponent.hpp
Labels: affects latest release, bug, frontend: C++11, frontend: Python3

#472 CMake: Optional ADIOS1 Wrapper Libs
  CHANGELOG.rst
  CMakeLists.txt
  src/IO/AbstractIOHandlerHelper.cpp
Labels: backend: ADIOS1, install, refactoring

#473 Docs: New First Steps
  CHANGELOG.rst
  docs/source/index.rst
  docs/source/usage/firstread.rst
  docs/source/usage/firststeps.rst
  docs/source/usage/firstwrite.rst
  docs/source/usage/parallel.rst
  docs/source/usage/serial.rst
Labels: documentation

#474 Docs: Invasive Tests not Default
  CHANGELOG.rst
  README.md
  docs/source/dev/buildoptions.rst
Labels: documentation, install, tests

#478 First Read/Write: Typos
  CHANGELOG.rst
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: documentation, frontend: C++11

#479 Doc: Clang Sanitize with Hidden Symbols
  CMakeLists.txt
Labels: documentation, install

#458 Python: Slice Protocol for Record Component
  CHANGELOG.rst
  examples/2_read_serial.py
  examples/3_write_serial.py
  examples/5_write_parallel.py
  examples/7_extended_write_serial.py
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, api: new, bug, frontend: Python3

#480 Readme: New First Steps Link
  README.md
Labels: documentation

#456 OpenMPI Root: Tailored
  CHANGELOG.rst
  CMakeLists.txt
Labels: MPI, affects latest release, bug, install, tests

#486 Typo: First Read
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: documentation

#487 CI: Move to Python 3.7, drop 2.7
  .appveyor.yml
  .travis.yml
  .travis/spack/packages.yaml
Labels: continuous integration

#483 Doc: AccessType
  CHANGELOG.rst
  include/openPMD/IO/AccessType.hpp
Labels: documentation

#428 CI: Shared
  .travis.yml
  CMakeLists.txt
Labels: continuous integration

#488 CI: +UBSan +Python +MPI +HF5
  .travis.yml
  .travis/sanitizer/clang/Leak.supp
  CMakeLists.txt
Labels: continuous integration
