Repository openPMD/openPMD-api, pull requests merged in 2019-06, with the labels that each got.

#518 Allow flushing before defining position and positionOffset components of particle species
  include/openPMD/ParticleSpecies.hpp
  src/ParticleSpecies.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: internal, refactoring

#519 Follow-up – Allow flushing before defining position and positionOffset components of particle species
  src/ParticleSpecies.cpp
Labels: bug, internal

#523 Dockerfile: manylinux2010
  .dockerignore
  Dockerfile
  README.md
  docs/source/dev/release.rst
  docs/source/install/install.rst
  setup.py
  share/openPMD/cmake/FindADIOS.cmake
Labels: install, third party

#525 pybind11: v2.3.0+
  .travis.yml
  .travis/sanitizer/clang/Leak.supp
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  requirements.txt
  share/openPMD/thirdParty/pybind11/CONTRIBUTING.md
  share/openPMD/thirdParty/pybind11/README.md
  share/openPMD/thirdParty/pybind11/include/pybind11/attr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/complex.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/descr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/init.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/typeid.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen.h
  share/openPMD/thirdParty/pybind11/include/pybind11/embed.h
  share/openPMD/thirdParty/pybind11/include/pybind11/functional.h
  share/openPMD/thirdParty/pybind11/include/pybind11/iostream.h
  share/openPMD/thirdParty/pybind11/include/pybind11/numpy.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/tools/FindPythonLibsNew.cmake
  share/openPMD/thirdParty/pybind11/tools/mkdoc.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Config.cmake.in
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: frontend: Python3, third party

#521 CMake Win: Install Paths Cache
  CMakeLists.txt
Labels: affects latest release, bug, install

#526 Issue Template: Install Problem
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/install_problem.md
Labels: documentation, install

#527 setup_requires: pyproject.toml (PEP-518)
  MANIFEST.in
  pyproject.toml
  requirements.txt
Labels: frontend: Python3, install

#522 Update Badges
  README.md
  docs/source/install/install.rst
Labels: documentation, install, third party

#529 Allow to write empty datasets
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  src/RecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: api: new, frontend: C++11
