Repository openPMD/openPMD-api, pull requests merged in 2019-11, with the labels that each got.

#582 Python: Fix Shadowing a Variable in Mesh
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  src/binding/python/Mesh.cpp
Labels: frontend: Python3, install, warning

#584 Corrected typo in README
  README.md
Labels: documentation

#583 Docs: MPI Contracts
  docs/source/details/mpi.rst
  docs/source/index.rst
Labels: MPI, documentation

#587 JSON: Always Enabled
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  Singularity
  docs/Doxyfile
  docs/source/backends/json.rst
  docs/source/dev/buildoptions.rst
  docs/source/install/install.rst
  include/openPMD/IO/Format.hpp
  include/openPMD/IO/JSON/JSONFilePosition.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/config.hpp.in
  openPMDConfig.cmake.in
  src/IO/JSON/JSONFilePosition.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/binding/python/openPMD.cpp
  test/SerialIOTest.cpp
Labels: backend: JSON, install

#588 Temporary fix for "ADIOS2 backend broken on post-2.5.0 master"
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: affects latest release, backend: ADIOS2, bug

#592 Docs: First Write Explains unitDimension
  docs/source/usage/firstwrite.rst
Labels: documentation

#594 Doc: Improve Pip Install
  CHANGELOG.rst
  README.md
  docs/source/dev/sphinx.rst
  docs/source/install/install.rst
Labels: documentation, frontend: Python3, install

#595 Fix OSX setup.py: @loader_path
  CHANGELOG.rst
  setup.py
Labels: bug, frontend: Python3, install, machine/system

#596 Fix mpi4py Examples: import first
  CHANGELOG.rst
  examples/4_read_parallel.py
  examples/5_write_parallel.py
Labels: MPI, bug, documentation, frontend: Python3, tests

#598 Link to Datasets added to Doc
  docs/source/usage/examples.rst
Labels: documentation

#600 Docs: Pip No-Binary Deps
  CHANGELOG.rst
  README.md
  docs/source/install/install.rst
Labels: bug, documentation, frontend: Python3, install, third party

#599 Python3 in docs cmake instructions section
  README.md
  docs/source/install/install.rst
Labels: documentation, install

#602 setup.py / pip: Static Build by default
  CHANGELOG.rst
  Dockerfile
  setup.py
Labels: affects latest release, bug, frontend: Python3, install, third party

#604 Readme: Update ADIOS Homepage & CMake
  README.md
Labels: documentation

#606 Changelog: Update More PRs for 0.10.0
  CHANGELOG.rst
Labels: documentation

#605 ADIOS1: Keep Default for Now
  NEWS.rst
  docs/source/backends/adios1.rst
  docs/source/backends/adios2.rst
  src/Series.cpp
Labels: backend: ADIOS1, backend: ADIOS2, documentation

#608 Sphinx: Minor Formatting Updates
  CHANGELOG.rst
  docs/source/backends/adios1.rst
  docs/source/backends/adios2.rst
  docs/source/backends/hdf5.rst
  docs/source/backends/json.rst
  docs/source/dev/design.rst
  docs/source/index.rst
  docs/source/install/install.rst
Labels: documentation

#609 ADIOS1: Fix _FOUND False Positive (Version)
  CHANGELOG.rst
  share/openPMD/cmake/FindADIOS.cmake
Labels: affects latest release, backend: ADIOS1, bug, install

#611 Python: Get Unit Dimension
  CHANGELOG.rst
  src/binding/python/BaseRecord.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, frontend: Python3

#610 Series: Throw on Dummy Handler
  CHANGELOG.rst
  NEWS.rst
  src/IO/AbstractIOHandlerHelper.cpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
Labels: affects latest release, api: breaking, bug, frontend: C++11, frontend: Python3

#607 Release: 0.10.0-alpha
  CHANGELOG.rst
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#612 Post 0.10.0-alpha Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#614 ADIOS2: Fix C++17 Build
  CHANGELOG.rst
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: affects latest release, backend: ADIOS2, bug

#615 Dockerfile: Python 3.8 Manylinux
  Dockerfile
Labels: frontend: Python3, install, third party

#617 NVCC: No Visibility Attribute
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
Labels: affects latest release, bug, machine/system, warning

#618 MPark.Variant: Hotfix NVCC C++14
  CHANGELOG.rst
  share/openPMD/thirdParty/variant/include/mpark/variant.hpp
Labels: affects latest release, bug, machine/system, third party

#619 Community: Code of Conduct
  CHANGELOG.rst
  CODE_OF_CONDUCT.rst
  docs/source/coc.rst
  docs/source/index.rst
Labels: documentation
