Repository openPMD/openPMD-api, pull requests merged in 2019-07, with the labels that each got.

#528 Remove dummy dataset writing from RecordComponent::flush()
  src/RecordComponent.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, internal

#530 Docs: ADIOS2 v2.4.0+
  CMakeLists.txt
  README.md
  docs/source/dev/dependencies.rst
Labels: documentation

#531 Changelog: Catch Up 0.9.0
  CHANGELOG.rst
Labels: documentation

#533 CMake: HDF5 Linkage is Private
  CHANGELOG.rst
  CMakeLists.txt
Labels: backend: HDF5, bug, install

#535 pkg-config: support static linking
  CHANGELOG.rst
  CMakeLists.txt
  README.md
Labels: install

#537 Python Manifest: add .in files
  CHANGELOG.rst
  MANIFEST.in
Labels: bug, frontend: Python3, install

#536 Release: 0.9.0-alpha
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#540 Post 0.9.0-alpha Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#541 Docs: Minor Typos & Format
  README.md
  docs/source/dev/release.rst
  docs/source/index.rst
Labels: documentation

#543 Clang<4.0: Increase Tpl Recursion Depth
  CHANGELOG.rst
  CMakeLists.txt
Labels: affects latest release, bug, frontend: Python3, machine/system

#544 CMake: Skip Python Examples w/o HDF5
  CHANGELOG.rst
  CMakeLists.txt
Labels: affects latest release, backend: HDF5, bug, frontend: Python3, install, tests
