Repository openPMD/openPMD-api, pull requests merged in 2019-12, with the labels that each got.

#621 Docs: All Contributors
  .rodare.json
  README.md
Labels: documentation

#613 Improve attribute read time in ADIOS2 backend
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, workaround

#622 Add Container::contains
  CHANGELOG.rst
  docs/source/usage/firstread.rst
  include/openPMD/backend/Container.hpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, documentation, frontend: C++11, frontend: Python3

#623 Release: 0.10.1-alpha
  CHANGELOG.rst
  README.md
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#624 Post 0.10.1-alpha Changelog Template
  CHANGELOG.rst
  docs/source/conf.py
  docs/source/dev/release.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#627 LGTM: Badges and CI
  README.md
  include/openPMD/backend/Attribute.hpp
  src/RecordComponent.cpp
Labels: continuous integration

#628 Rule of Three: Add Missing Assignment Ops
  CHANGELOG.rst
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/Record.hpp
  include/openPMD/backend/BaseRecord.hpp
  src/Iteration.cpp
  src/Record.cpp
Labels: affects latest release, bug, frontend: C++11, internal

#630 LGTM: Add ADIOS1 and HDF5 Deps
  .lgtm.yml
Labels: MPI, backend: ADIOS1, backend: HDF5, continuous integration

#632 Add Missing Virtual Destructors
  .clang-tidy
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractFilePosition.hpp
  include/openPMD/IO/DummyIOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandlerImpl.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/ParticlePatches.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Record.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/MeshRecordComponent.hpp
  include/openPMD/backend/PatchRecord.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/DummyIOHandler.cpp
  src/IO/JSON/JSONIOHandler.cpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/backend/PatchRecord.cpp
  src/backend/Writable.cpp
Labels: affects latest release, bug, internal

#629 Spack: No microarch
  .travis.yml
  .travis/spack/packages.yaml
Labels: bug, continuous integration, third party, workaround

#634 Backends: Prefix Error Messages
  CHANGELOG.rst
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
Labels: backend: ADIOS1, backend: ADIOS2, backend: HDF5, backend: JSON, refactoring

#635 ADIOS1: Skip Invalid Scalar Particle Records
  CHANGELOG.rst
  src/ParticleSpecies.cpp
Labels: backend: ADIOS1, workaround

#637 Release: 0.10.2-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#638 Post 0.10.2-alpha Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#640 Source Files: Fix Includes
  CHANGELOG.rst
  src/Iteration.cpp
  src/backend/Writable.cpp
Labels: bug

#641 Legacy HDF5 libSplash Handling
  CHANGELOG.rst
  src/IO/HDF5/HDF5IOHandler.cpp
  src/RecordComponent.cpp
  test/CoreTest.cpp
Labels: backend: HDF5, workaround

#643 Allows multiple flush on the same file
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: affects latest release, backend: HDF5, bug

#644 Docs: Grants & New Contributors
  .rodare.json
  README.md
Labels: documentation

#645 Release: 0.10.3-alpha
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#646 Post 0.10.3-alpha Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation
