Repository openPMD/openPMD-api, pull requests merged in 2020-12, with the labels that each got.

#832 Fix: Win ClangCL
  include/openPMD/Datatype.hpp
Labels: affects latest release, bug, machine/system

#802 Add ::availableChunks call to Record Component types
  CMakeLists.txt
  include/openPMD/ChunkInfo.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  src/ChunkInfo.cpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/backend/BaseRecordComponent.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/ChunkInfo.cpp
  src/binding/python/openPMD.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new

#822 Allow reading a file-based series with many iterations without crashing the number of file handles
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/Option.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, internal

#835 HDF5: Fix File Handle Open
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5, bug

#830 added env option OPENPMD_HDF5_ALIGNMENT
  docs/source/backends/hdf5.rst
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
Labels: backend: HDF5

#838 Determinize destruction order of files in ADIOS2
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, bug

#837 Explicitly record close status if temporarily closing
  include/openPMD/Iteration.hpp
  src/Iteration.cpp
  src/Series.cpp
Labels: bug, internal

#836 Series: Drop GCC 4.8
  src/Series.cpp
Labels: internal, machine/system

#839 NLohmann-JSON: 3.9.1+
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/json/CMakeLists.txt
  share/openPMD/thirdParty/json/LICENSE.MIT
  share/openPMD/thirdParty/json/cmake/download_test_data.cmake
  share/openPMD/thirdParty/json/cmake/nlohmann_jsonConfigVersion.cmake.in
  share/openPMD/thirdParty/json/cmake/pkg-config.pc.in
  share/openPMD/thirdParty/json/single_include/nlohmann/json.hpp
Labels: affects latest release, bug, machine/system, third party

#841 FindADIOS Warning: CMake 2.8.12+
  share/openPMD/cmake/FindADIOS.cmake
Labels: backend: ADIOS1, install, warning

#844 CI: Update LGTM packages
  .lgtm.yml
Labels: continuous integration

#843 clang-tidy: no modernize-use-auto
  .clang-tidy
Labels: tests

#818 JSON configuration on the dataset level
  docs/source/details/adios2.json
  docs/source/details/backendconfig.rst
  include/openPMD/Dataset.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/IOTask.hpp
  src/Dataset.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/RecordComponent.cpp
  src/backend/PatchRecordComponent.cpp
  src/binding/python/Dataset.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, backend: ADIOS2

#847 Explicitly set SubStreams for available_chunks parallel test
  test/ParallelIOTest.cpp
Labels: backend: ADIOS2

#842 Test: HiPACE I/O Pattern
  test/ParallelIOTest.cpp
Labels: MPI, tests

#849 Test Case: FBPIC Empty HDF5
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
  src/IO/HDF5/HDF5IOHandler.cpp
  src/RecordComponent.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, backend: HDF5, bug, internal, tests

#851 Windows: Less Verbose Warnings
  CMakeLists.txt
Labels: machine/system, warning

#850 Fix Python Data_Order
  NEWS.rst
  examples/3a_write_thetaMode_serial.py
  src/binding/python/Mesh.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, api: breaking, bug, frontend: Python3

#848 IO Test: Check data over time
  test/ParallelIOTest.cpp
Labels: MPI, tests, third party

#852 Wheels for Windows (64bit)
  .github/workflows/build.yml
  library_builders.bat
  library_builders.sh
Labels: continuous deployment, frontend: Python3, machine/system

#570 Streaming Support
  .github/ci/sanitizer/clang/Leak.supp
  CMakeLists.txt
  docs/source/backends/adios2.rst
  docs/source/details/backendconfig.rst
  docs/source/index.rst
  docs/source/usage/10_streaming_read.cpp
  docs/source/usage/10_streaming_read.py
  docs/source/usage/10_streaming_write.cpp
  docs/source/usage/10_streaming_write.py
  docs/source/usage/streaming.rst
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  examples/10_streaming_write.cpp
  examples/10_streaming_write.py
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/Format.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/Series.hpp
  include/openPMD/Streaming.hpp
  include/openPMD/helper/list_series.hpp
  src/Format.cpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/MeshRecordComponent.cpp
  src/binding/python/Helper.cpp
  src/binding/python/Series.cpp
  src/helper/list_series.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, backend: ADIOS2

#854 CI: set oldest supported macOS
  .github/workflows/unix.yml
Labels: machine/system, tests

#853 Docs: PyPI Support for Windows on x86-64
  README.md
  docs/source/install/install.rst
Labels: documentation, install

#834 added option to assign workload on rank
  docs/source/usage/benchmarks.rst
  examples/8a_benchmark_write_parallel.cpp
Labels: MPI, tests

#859 Python: Properties in Series, Mesh, ...
  NEWS.rst
  docs/source/usage/firstwrite.rst
  examples/3a_write_thetaMode_serial.py
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  src/binding/python/Attributable.cpp
  src/binding/python/ChunkInfo.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/Series.cpp
Labels: api: breaking, frontend: Python3

#860 Rename WrittenChunkInfo.mpi_rank -> WrittenChunkInfo.sourceID
  include/openPMD/ChunkInfo.hpp
  src/ChunkInfo.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/binding/python/ChunkInfo.cpp
  test/ParallelIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: breaking
