Repository openPMD/openPMD-api, pull requests merged in 2020-05, with the labels that each got.

#728 Examples: Fix ED-PIC "weighting"
  CHANGELOG.rst
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
Labels: tests

#733 Remove noisy ADIOS2 JSON warning
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, warning

#735 Python: More Idiomatic Unit Properties
  NEWS.rst
  docs/source/usage/firstwrite.rst
  examples/3a_write_thetaMode_serial.py
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/binding/python/UnitDimension.hpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/PatchRecord.cpp
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
Labels: frontend: Python3, refactoring

#739 Tests/Examples: Create Valid Files
  CHANGELOG.rst
  examples/1_structure.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, tests

#738 Tests: Validate Created Files
  .travis.yml
  CHANGELOG.rst
  share/openPMD/validate_files.sh
Labels: backend: HDF5, tests

#743 Access: Deprecate Carefully
  include/openPMD/IO/Access.hpp
Labels: bug, machine/system

#744 ICC: C++14 Typedef Deprecation
  include/openPMD/IO/Access.hpp
Labels: bug, frontend: C++11, third party, workaround

#747 Version Compare Macro
  CHANGELOG.rst
  include/openPMD/version.hpp
Labels: api: new

#745 Add Checks to *dynamic_cast
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/auxiliary/DerefDynamicCast.hpp
  include/openPMD/benchmark/mpi/MPIBenchmark.hpp
  include/openPMD/openPMD.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  test/AuxiliaryTest.cpp
Labels: refactoring
