Repository openPMD/openPMD-api, pull requests merged in 2020-04, with the labels that each got.

#711 Record(Component) scalar/constant/empty
  CHANGELOG.rst
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  src/Mesh.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/backend/BaseRecordComponent.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: frontend: C++11, frontend: Python3

#712 GitHub Checkout Action: v2
  .github/workflows/source.yml
  CHANGELOG.rst
Labels: tests, third party

#653 MPI Benchmark: Doxygen Params
  docs/Doxyfile
  include/openPMD/benchmark/mpi/MPIBenchmark.hpp
  include/openPMD/benchmark/mpi/MPIBenchmarkReport.hpp
  include/openPMD/benchmark/mpi/RandomDatasetFiller.hpp
Labels: documentation

#569 Advanced backend configuration via JSON
  CMakeLists.txt
  docs/source/backends/json.rst
  docs/source/details/adios2.json
  docs/source/details/backendconfig.rst
  docs/source/details/config_layout.json
  docs/source/index.rst
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/JSON.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Series.cpp
  src/auxiliary/JSON.cpp
  src/binding/python/Series.cpp
  test/SerialIOTest.cpp
Labels: api: new, backend, backend: ADIOS1, backend: ADIOS2, backend: HDF5, backend: JSON

#714 CI: Fix OSX Numpy Install
  .travis.yml
Labels: continuous integration, machine/system

#713 MeshRecordComponent: Python position
  CHANGELOG.rst
  examples/3a_write_thetaMode_serial.py
  include/openPMD/backend/MeshRecordComponent.hpp
  src/binding/python/MeshRecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: Python3

#715 CI scripts: Rename Directory
  .appveyor.yml
  .github/ci/sanitizer/clang/Leak.supp
  .github/ci/spack/compilers.yaml
  .github/ci/spack/config.yaml
  .github/ci/spack/packages.yaml
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/repostructure.rst
  docs/source/install/install.rst
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
Labels: continuous integration

#716 Docs: Autodeploy PyPI Wheels
  README.md
  docs/source/install/install.rst
  docs/source/maintenance/release.rst
  docs/source/maintenance/requirements.txt
Labels: continuous deployment, documentation, frontend: Python3

#717 CD: Add Travis Architectures
  .github/workflows/build.yml
  .travis.yml
  library_builders.sh
Labels: continuous deployment, machine/system

#718 Wheels: Cleanup, Prep. i686 and aarch64
  .github/workflows/build.yml
  .travis.yml
  library_builders.sh
Labels: continuous deployment

#719 Wheels on GitHub Action: macOS 10.9+
  .github/workflows/build.yml
Labels: continuous deployment, machine/system, third party

#720 Python: Add __init__.py Facade
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  setup.py
  src/binding/python/openPMD.cpp
  src/binding/python/openpmd_api/__init__.py
  test/python/unittest/API/APITest.py
Labels: frontend: Python3, install

#721 openpmd-ls: install in setuptools
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  include/openPMD/cli/ls.hpp
  setup.py
  src/binding/python/Helper.cpp
  src/binding/python/openpmd_api/__init__.py
  src/binding/python/openpmd_api/cli.py
  src/cli/ls.cpp
Labels: frontend: Python3, install, third party

#722 README: Fix Python Snippet Alias
  CHANGELOG.rst
  README.md
Labels: affects latest release, bug, documentation, frontend: Python3

#724 Python CLI: Module Support
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  docs/source/utilities/cli.rst
  setup.py
  share/openPMD/download_samples.ps1
  src/binding/python/openpmd_api/ls/__init__.py
  src/binding/python/openpmd_api/ls/__main__.py
Labels: frontend: Python3

#725 Docs: Brew Install
  CHANGELOG.rst
  NEWS.rst
  README.md
  docs/source/details/backendconfig.rst
  docs/source/install/brew.svg
  docs/source/install/install.rst
  docs/source/maintenance/release.rst
Labels: documentation, install, third party

#727 CI: Cygwin GitHub Action
  .github/workflows/cygwin.yml
Labels: continuous integration, machine/system
