Repository openPMD/openPMD-api, pull requests merged in 2020-07, with the labels that each got.

#758 Spack: apple-clang
  .github/ci/spack/compilers.yaml
  .github/ci/spack/packages.yaml
  .travis.yml
Labels: continuous integration, machine/system

#759 Travis CI: Add Clang 10.0 on Bionic
  .github/ci/spack/compilers.yaml
  .github/ci/spack/packages.yaml
  .travis.yml
Labels: continuous integration

#737 Spack: Environment File
  .gitignore
  CHANGELOG.rst
  docs/source/dev/dependencies.rst
  spack.yaml
Labels: documentation, install, third party

#762 Add .editorconfig file
  .editorconfig
  .github/workflows/source/hasNonASCII
Labels: documentation, tools

#763 Record Component: Fix Formatting
  include/openPMD/RecordComponent.hpp
Labels: cosmetic

#764 Datatype: Fix missing include
  CHANGELOG.rst
  include/openPMD/Datatype.hpp
Labels: affects latest release, bug

#746 Add functionality to close a file
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/BaseRecord.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/ParticleSpecies.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/binding/python/Iteration.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: C++11

#754 ADIOS2 2.6.0+
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ci/spack/packages.yaml
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  README.md
  docs/source/dev/dependencies.rst
Labels: backend: ADIOS2, continuous integration, documentation, tests, third party
