Repository openPMD/openPMD-api, pull requests merged in 2020-10, with the labels that each got.

#788 ICC: Fix Export
  include/openPMD/auxiliary/Export.hpp
Labels: affects latest release, bug, internal, machine/system

#789 Iteration: Fix Segfault with ICC during Write
  src/Iteration.cpp
Labels: affects latest release, bug, internal, machine/system

#793 add comment on lib64
  docs/source/install/install.rst
Labels: documentation

#797 Typo fix in docs for ADIOS1
  docs/source/backends/adios1.rst
Labels: documentation

#799 Conda: Recommend Fresh Env
  README.md
  docs/source/install/install.rst
Labels: documentation, frontend: Python3, install, third party

#795 HDF5: Status Checks
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5, warning

#791 CMake Warnings: ICC & Root Project
  CMakeLists.txt
  examples/7_extended_write_serial.cpp
  src/Series.cpp
Labels: install, machine/system, warning

#800 CI: Sanitize only project
  .travis.yml
Labels: continuous integration

#796 add missing python interface (read/write) for machine
  docs/source/usage/firstwrite.rst
  src/binding/python/Series.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: Python3

#801 Be less verbose about missing helper attributes for boolean attributes in ADIOS2
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, warning

#538 Record_Component.make_empty()
  include/openPMD/RecordComponent.hpp
  src/RecordComponent.cpp
  src/binding/python/RecordComponent.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: Python3

#806 Add Optional based on variantSrc::variant
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/auxiliary/Option.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/auxiliary/VariantSrc.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/AuxiliaryTest.cpp
Labels: internal

#809 Sphinx/rst: Fix Warnings
  CHANGELOG.rst
  docs/source/dev/dependencies.rst
Labels: documentation, warning

#810 CMake: Re-Order Dependency Checks
  CMakeLists.txt
Labels: install, refactoring
