Repository openPMD/openPMD-api, pull requests merged in 2020-01, with the labels that each got.

#649 Docs first read python typo
  docs/source/usage/firstread.rst
Labels: affects latest release, bug, documentation, frontend: Python3

#648 BaseRecord: Overwrite Erase with Iterator
  include/openPMD/backend/BaseRecord.hpp
  test/AuxiliaryTest.cpp
  test/SerialIOTest.cpp
Labels: frontend: C++11, warning

#650 MPark.Variant: Update NVCC Hotfix C++14
  CHANGELOG.rst
  share/openPMD/thirdParty/variant/include/mpark/variant.hpp
Labels: bug, machine/system, third party, workaround

#652 Clang & GCC: Woverloaded-virtual, Wextra-semi
  CMakeLists.txt
  include/openPMD/Datatype.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
Labels: continuous integration, warning

#654 Doxygen: Fix Many Warnings
  .github/workflows/source.yml
  .github/workflows/source/buildDoxygen
  CMakeLists.txt
  docs/Doxyfile
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImplCommon.hpp
  include/openPMD/UnitDimension.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/openPMD.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/Record.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/UnitDimension.cpp
  src/binding/python/openPMD.cpp
Labels: documentation, refactoring, warning

#656 ADIOS2: Environment Variable for Engine
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/backends/adios2.rst
  docs/source/dev/dependencies.rst
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, documentation

#657 Defaults for Date & Software Attributes
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/Date.hpp
  include/openPMD/auxiliary/Deprecated.hpp
  include/openPMD/openPMD.hpp
  src/Series.cpp
  src/auxiliary/Date.cpp
  src/binding/python/Series.cpp
  test/CoreTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: C++11, frontend: Python3, internal

#659 Remove Unreachable Code
  CMakeLists.txt
  README.md
  include/openPMD/Datatype.hpp
  include/openPMD/backend/Attribute.hpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/binding/python/RecordComponent.cpp
Labels: warning

#660 CI: Less on Travis
  .github/workflows/source.yml
  .travis.yml
Labels: continuous integration

#661 Docs: Backend Feature Matrix
  CHANGELOG.rst
  docs/source/backends/overview.rst
  docs/source/index.rst
Labels: documentation

#662 Overload ostream function operator<< not in std
  CHANGELOG.rst
  include/openPMD/Datatype.hpp
  include/openPMD/IterationEncoding.hpp
  include/openPMD/Mesh.hpp
  src/Datatype.cpp
  src/IterationEncoding.cpp
  src/Mesh.cpp
Labels: affects latest release, bug

#663 Attribute Constructor: Move Argument
  CHANGELOG.rst
  include/openPMD/backend/Attribute.hpp
Labels: refactoring

#664 Spack: ADIOS1 By Default
  CHANGELOG.rst
  NEWS.rst
  README.md
  docs/source/install/install.rst
Labels: documentation

#665 Query API version & Variants at Runtime
  CHANGELOG.rst
  CMakeLists.txt
  include/openPMD/version.hpp
  src/binding/python/openPMD.cpp
  src/config.cpp
  src/version.cpp
  test/CoreTest.cpp
Labels: api: new

#667 README: CMake FetchContent
  CHANGELOG.rst
  README.md
Labels: documentation, install

#669 CI: HDF5 Independent Stores Test
  .travis.yml
  CHANGELOG.rst
  test/ParallelIOTest.cpp
Labels: MPI, backend: HDF5, continuous integration, tests

#670 CI: Add MPICH Tests
  .travis.yml
  .travis/spack/compilers.yaml
  .travis/spack/packages.yaml
  CHANGELOG.rst
Labels: MPI, continuous integration

#668 Series Test: FileBased Independent
  test/ParallelIOTest.cpp
Labels: MPI, continuous integration, internal, tests

#673 CI: Prefer ADIOS2 in MPI-Parallel Test
  .travis.yml
  test/ParallelIOTest.cpp
Labels: MPI, backend: ADIOS1, backend: ADIOS2, continuous integration

#674 ADIOS1: Create Attribute-Only Files
  CHANGELOG.rst
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandler.hpp
  include/openPMD/Series.hpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, backend: ADIOS1, bug, tests

#672 Parallel Test: Flush fileBased Some
  test/ParallelIOTest.cpp
Labels: MPI, affects latest release, backend: ADIOS1, bug

#676 ADIOS2: New Default for BP
  .travis.yml
  CHANGELOG.rst
  NEWS.rst
  README.md
  docs/source/backends/adios1.rst
  docs/source/backends/adios2.rst
  docs/source/install/install.rst
  src/Series.cpp
Labels: backend: ADIOS1, backend: ADIOS2, documentation

#677 Parallel HDF5: Independent I/O By Default
  .travis.yml
  CHANGELOG.rst
  NEWS.rst
  docs/source/backends/hdf5.rst
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  test/ParallelIOTest.cpp
Labels: backend: HDF5

#681 CI: Non-ASCII Characters
  .github/workflows/source.yml
  .github/workflows/source/hasNonASCII
  .github/workflows/source/hasTabs
Labels: continuous integration
