Repository openPMD/openPMD-api, pull requests merged in 2020-02, with the labels that each got.

#685 ADIOS1 & H5: More Backend Docs
  CHANGELOG.rst
  docs/source/backends/adios1.rst
  docs/source/backends/hdf5.rst
Labels: backend: ADIOS1, backend: HDF5, bug, documentation, third party

#684 Format: Determine from Name Public
  CHANGELOG.rst
  CMakeLists.txt
  include/openPMD/IO/Format.hpp
  include/openPMD/Series.hpp
  include/openPMD/openPMD.hpp
  src/Format.cpp
  src/Series.cpp
Labels: api: new, frontend: C++11

#686 Tests: Multiple Series Active
  CHANGELOG.rst
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS1, bug, tests, third party

#682 LGTM: OpenMPI-Enabled
  .lgtm.yml
Labels: MPI, backend: ADIOS1, backend: HDF5, continuous integration

#679 added accesstype check before adding read operations
  .rodare.json
  CHANGELOG.rst
  README.md
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, backend: ADIOS1, bug, workaround
