Repository openPMD/openPMD-api, pull requests merged in 2020-06, with the labels that each got.

#752 Extended Write: Warning MSVC
  CHANGELOG.rst
  examples/7_extended_write_serial.cpp
Labels: machine/system, warning

#723 Travis CI: Add GCC 9.3.0 on Bionic
  .github/ci/spack/compilers.yaml
  .github/ci/spack/packages.yaml
  .travis.yml
  CHANGELOG.rst
Labels: continuous integration

#751 CMake: Subproject Cleanup
  .github/workflows/cygwin.yml
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  setup.py
Labels: install, refactoring

#753 Python Container: Redundant Move
  CHANGELOG.rst
  src/binding/python/Container.cpp
Labels: frontend: Python3, invalid, warning

#706 Add particle info in serial example read
  CHANGELOG.rst
  examples/2_read_serial.cpp
  examples/2_read_serial.py
Labels: documentation, tests

#755 CI: ADIOS 2.5.0 & CMake 3.12.0+
  .github/ci/spack/packages.yaml
  .travis.yml
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/dev/dependencies.rst
  pyproject.toml
  setup.py
Labels: backend: ADIOS2, bug, machine/system, tests, third party, workaround

#757 Style Check: Eval-uable
  .github/workflows/source/hasEOLwhiteSpace
  .github/workflows/source/hasTabs
Labels: continuous integration
