Repository openPMD/openPMD-api, pull requests merged in 2020-11, with the labels that each got.

#803 added tests 8a & 8b to do 1D/2D mesh writing and reading
  CMakeLists.txt
  docs/source/usage/examples.rst
  examples/8a_benchmark_write1D2D_parallel.cpp
  examples/8b_benchmark_read1D2D_parallel.cpp
  include/openPMD/benchmark/MemoryProfiler.hpp
  include/openPMD/benchmark/Timer.hpp
Labels: tests

#812 Fix Series Attributes: Read Defaults
  src/Series.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, internal

#785 Add missing CLOSE_FILE IO task to Parallel ADIOS1backend
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  test/ParallelIOTest.cpp
Labels: affects latest release, backend: ADIOS1, bug

#817 Docs: Franz with CASUS
  .rodare.json
  README.md
Labels: documentation

#819 First Read: Slice
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: documentation, frontend: C++11, frontend: Python3

#820 CI: Cygwin Remove
  .github/workflows/cygwin.yml
Labels: continuous integration

#823 Travis -> GH Action
  .clang-tidy
  .github/ci/spack-envs/clang5_nopy_nompi_h5/spack.yaml
  .github/ci/spack-envs/clang5_nopy_ompi_h5_ad1_ad2_bp3/spack.yaml
  .github/ci/spack-envs/clangtidy_nopy_ompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/gcc5_py36_ompi_h5_ad1_ad2/spack.yaml
  .github/workflows/dependencies/install_spack
  .github/workflows/unix.yml
  .travis.yml
  examples/8b_benchmark_read1D2D_parallel.cpp
  src/Iteration.cpp
  src/backend/PatchRecord.cpp
Labels: continuous integration

#821 pybind11: v2.4.3+
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  share/openPMD/thirdParty/pybind11/README.md
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/chrono.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/functional.h
  share/openPMD/thirdParty/pybind11/include/pybind11/iostream.h
  share/openPMD/thirdParty/pybind11/include/pybind11/numpy.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/pybind11/__init__.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/tools/FindPythonLibsNew.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: frontend: Python3, third party

#825 C++14
  .appveyor.yml
  .github/workflows/dependencies/install_spack
  .github/workflows/unix.yml
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/citation.rst
  docs/source/dev/dependencies.rst
  docs/source/usage/firstwrite.rst
  include/openPMD/Datatype.hpp
  include/openPMD/IO/Access.hpp
  include/openPMD/Series.hpp
  include/openPMD/auxiliary/Deprecated.hpp
  include/openPMD/binding/python/Numpy.hpp
  include/openPMD/binding/python/Variant.hpp
  include/openPMD/openPMD.hpp
  setup.py
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/binding/python/Attributable.cpp
  test/SerialIOTest.cpp
Labels: install

#827 CI: Fix Spack Cache
  .github/workflows/dependencies/install_spack
Labels: bug, continuous integration

#826 Modernize: C++11/14
  .clang-tidy
  examples/5_write_parallel.cpp
  examples/8a_benchmark_write1D2D_parallel.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONFilePosition.cpp
  src/ParticleSpecies.cpp
  src/auxiliary/Date.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
  src/cli/ls.cpp
  test/ParallelIOTest.cpp
Labels: backend: ADIOS2, backend: HDF5, backend: JSON, internal, tests

#828 Python: 3.6 - 3.9
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  NEWS.rst
  README.md
  docs/source/dev/dependencies.rst
  setup.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: frontend: Python3

#816 8a/8b benchmarks renamed and added 3D support
  CMakeLists.txt
  docs/source/index.rst
  docs/source/usage/benchmarks.rst
  docs/source/usage/examples.rst
  examples/8a_benchmark_write1D2D_parallel.cpp
  examples/8a_benchmark_write_parallel.cpp
  examples/8b_benchmark_read1D2D_parallel.cpp
  examples/8b_benchmark_read_parallel.cpp
Labels: tests
