Repository openPMD/openPMD-api, pull requests merged in 2021-05, with the labels that each got.

#972 Variant.hpp: size_t include
  include/openPMD/auxiliary/Variant.hpp
Labels: affects latest release, bug, internal, machine/system

#976 RTD: Limit Sphinx to <4.0
  docs/requirements.txt
Labels: affects latest release, documentation, third party, workaround

#975 Wheels: 0.13.4
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment, frontend: Python3

#977 pybind11: v2.6.2+
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  share/openPMD/thirdParty/pybind11/CMakeLists.txt
  share/openPMD/thirdParty/pybind11/README.rst
  share/openPMD/thirdParty/pybind11/include/pybind11/attr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/iostream.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/pybind11/setup_helpers.py
  share/openPMD/thirdParty/pybind11/tools/FindEigen3.cmake
  share/openPMD/thirdParty/pybind11/tools/FindPythonLibsNew.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Config.cmake.in
  share/openPMD/thirdParty/pybind11/tools/pybind11NewTools.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: frontend: Python3, third party

#978 CI: Source Tools Update
  .github/workflows/source/hasEOLwhiteSpace
  .github/workflows/source/hasNonASCII
  .github/workflows/source/hasTabs
Labels: continuous integration

#980 CMake: Expose Python LTO Control
  CHANGELOG.rst
  CMakeLists.txt
  README.md
  docs/source/install/install.rst
  setup.py
Labels: affects latest release, frontend: Python3, install

#981 SST tests: start reader a second after the writer
  CMakeLists.txt
  test/ParallelIOTest.cpp
Labels: backend: ADIOS2, tests

#971 Set a default QueueLimit of 2 in the ADIOS2/SST engine
  docs/source/backends/adios2.rst
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2

#988 Doc: Iteration close flush - fix typo
  docs/source/usage/workflow.rst
Labels: documentation

#979 HDF5Auxiliary: Check String Sizes
  src/IO/HDF5/HDF5Auxiliary.cpp
Labels: affects latest release, backend: HDF5, bug
