Repository openPMD/openPMD-api, pull requests merged in 2021-02, with the labels that each got.

#917 HDF5 Auxiliary: .cpp file
  CMakeLists.txt
  include/openPMD/IO/HDF5/HDF5Auxiliary.hpp
  src/IO/HDF5/HDF5Auxiliary.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5, refactoring

#918 Wheels: 0.13.2
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment, frontend: Python3

#813 Use ADIOS variables for openPMD attributes
  .github/workflows/unix.yml
  CMakeLists.txt
  docs/source/backends/adios2.rst
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2PreloadAttributes.hpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ADIOS2PreloadAttributes.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2

#919 MSVC: Proper __cplusplus macro
  CMakeLists.txt
Labels: install, machine/system

#924 Mesh & ParticleSpecies::seriesFlush
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Series.hpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/ParticleSpecies.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: C++11, frontend: Python3

#925 Attributable & Writable: seriesFlush
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Writable.hpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/backend/Attributable.cpp
  src/backend/Writable.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/ParticleSpecies.cpp
Labels: api: new, frontend: C++11, frontend: Python3

#929 Add Dependabot
  .github/dependabot.yml
Labels: continuous integration

#928 Docs: dev-centered development
  CONTRIBUTING.rst
  docs/source/dev/repostructure.rst
Labels: documentation

#923 ParticleSpecies: Read to pandas.DataFrame
  .github/workflows/unix.yml
  CMakeLists.txt
  examples/11_particle_dataframe.py
  src/binding/python/openpmd_api/DataFrame.py
  src/binding/python/openpmd_api/__init__.py
Labels: api: new, frontend: Python3

#930 CMake: Fix library type control
  CMakeLists.txt
Labels: bug, install

#904 Add openpmd-pipe.py command line tool
  CMakeLists.txt
  include/openPMD/Datatype.hpp
  src/binding/python/Attributable.cpp
  src/binding/python/openpmd_api/pipe/__init__.py
  src/binding/python/openpmd_api/pipe/__main__.py
  src/cli/pipe.py
Labels: tools

#932 pyproject.toml: build-backend
  pyproject.toml
Labels: frontend: Python3, install

#933 bp4_steps test: actually use nullcore engine
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, bug, tests

#913 Python: fix load_chunk to temporary
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, frontend: Python3

#886 Split Series into an internal and an external class
  docs/source/dev/design.rst
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/IOTask.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/BaseRecordComponent.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  src/backend/Writable.cpp
  src/binding/python/Attributable.cpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: api: breaking, bug, discussion, refactoring

#870 CI: ICC/ICPC & ICX/ICPX
  .github/workflows/dependencies/install_icc
  .github/workflows/dependencies/install_icx
  .github/workflows/unix.yml
  include/openPMD/DatatypeHelpers.hpp
Labels: continuous integration
