Repository openPMD/openPMD-api, pull requests merged in 2021-07, with the labels that each got.

#1019 Test for ADIOS2 Git sample
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, continuous integration, tests

#1018 Don't flush Series a second time after throwing an error
  include/openPMD/Series.hpp
  src/Iteration.cpp
  src/Series.cpp
  src/backend/Writable.cpp
Labels: affects latest release, bug, internal

#1027 Support Parallel HDF5 w/ CMake
  CMakeLists.txt
Labels: MPI, affects latest release, backend: HDF5, bug, install

#963 ParticleSpecies & RecordComponent Serialize
  examples/11_particle_dataframe.py
  include/openPMD/backend/Attributable.hpp
  include/openPMD/binding/python/Pickle.hpp
  src/RecordComponent.cpp
  src/backend/Attributable.cpp
  src/binding/python/ChunkInfo.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  test/CoreTest.cpp
  test/python/unittest/API/APITest.py
Labels: help wanted

#1031 SeriesImpl::flush_impl(): flushIOHandler = true default param
  include/openPMD/Series.hpp
  src/Iteration.cpp
  src/Series.cpp
  src/backend/Writable.cpp
Labels: cosmetic, frontend: C++14

#710 CMake: Update MPI Components
  .github/ci/spack-envs/clang8_py38_mpich_h5_ad1_ad2/spack.yaml
  .github/workflows/unix.yml
  CHANGELOG.rst
  CMakeLists.txt
Labels: MPI, install

#1030 Bug fix: Use Series::writeIterations() without explicit flushing
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  src/Series.cpp
  src/WriteIterations.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, frontend: C++14

#1034 GitHub: Update Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/install_problem.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#1033 Docs: Link Stream & Dataframe Examples
  docs/source/usage/examples.rst
Labels: documentation, frontend: C++14, frontend: Python3, tests

#1042 Mesh: Enable-If Float APIs
  include/openPMD/Mesh.hpp
  src/Mesh.cpp
Labels: affects latest release, bug, frontend: C++14

#1040 Datatype: Fix std::array template
  include/openPMD/Datatype.hpp
Labels: affects latest release, bug, frontend: C++14

#1041 Docs: makeConstant & Parallel HDF5
  docs/source/details/backendconfig.rst
  docs/source/details/mpi.rst
  test/ParallelIOTest.cpp
Labels: MPI, backend: HDF5, documentation

#1036 ADIOS2: More obvious error message if datatype cannot be found
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2

#1049 Use specific commit for downloaded samples
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
Labels: continuous integration, tests

#1047 Docs: Benchmark 8 Update
  docs/source/usage/benchmarks.rst
Labels: MPI, documentation, tests

#1050 Fix: PkgConfig w/ External Variant
  CMakeLists.txt
  openPMD.pc.in
Labels: affects latest release, bug, install

#1039 Dowload Samples: Optional Directory
  CMakeLists.txt
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
Labels: install, tests

#1051 Update Adios2 git sample tests
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, tests

#1053 Warnings: Unreachable Code & Unused Param
  examples/8b_benchmark_read_parallel.cpp
  include/openPMD/Datatype.hpp
Labels: warning

#1055 More Warnings: Unused/Unreachable
  examples/8a_benchmark_write_parallel.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5, warning

#1054 SerialIOTest: Fix CI Hang
  test/SerialIOTest.cpp
Labels: continuous integration, tests

#1035 availableChunks open logic (HDF5: Early Chunk Read)
  docs/source/details/mpi.rst
  docs/source/usage/streaming.rst
  include/openPMD/Iteration.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  src/Iteration.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/BaseRecordComponent.cpp
  test/SerialIOTest.cpp
Labels: backend: HDF5, bug

#1056 SerialIOTest: OPENPMD_TEST_NFILES_MAX
  .github/workflows/unix.yml
  test/SerialIOTest.cpp
Labels: continuous integration, tests

#1045 ADIOS2: Don't implicitly open files
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, bug

#1057 CoreTest: Lambda outside uneval context
  test/CoreTest.cpp
Labels: affects latest release, bug, tests

#1059 Series: fileBased no_such_file_error
  src/Series.cpp
Labels: affects latest release, bug, frontend: C++14

#1052 CI: Update & NVHPC
  .github/workflows/dependencies/install_nvcc11.sh
  .github/workflows/dependencies/install_nvhpc21-5.sh
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/nvidia.yml
  .github/workflows/source.yml
  .github/workflows/tooling.yml
  .github/workflows/unix.yml
Labels: continuous integration

#1060 Doc: Resize Examples (Particles)
  .github/workflows/tooling.yml
  CMakeLists.txt
  docs/source/usage/3b_write_resizable_particles.cpp
  docs/source/usage/3b_write_resizable_particles.py
  docs/source/usage/examples.rst
  examples/3b_write_resizable_particles.cpp
  examples/3b_write_resizable_particles.py
Labels: documentation

#1061 Docs: Move IOTasks Quoted Lines
  docs/source/dev/design.rst
  include/openPMD/IO/IOTask.hpp
Labels: documentation

#1066 Doc: Benchmark 8b Pack Parameter
  docs/source/usage/benchmarks.rst
Labels: MPI, documentation, tests

#1067 Fix C++17: ADIOS2IOHandler
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2, bug

#1063 Add Dataset(Extent) constructor to Python bindings
  examples/3b_write_resizable_particles.cpp
  examples/3b_write_resizable_particles.py
  src/binding/python/Dataset.cpp
Labels: frontend: Python3

#1065 Rename SeriesImpl → SeriesInterface, AttributableImpl → AttributableInterface
  docs/source/details/backendconfig.rst
  docs/source/dev/design.rst
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/IOTask.cpp
  src/Iteration.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/Writable.cpp
  test/CoreTest.cpp
Labels: affects latest release, api: breaking, frontend: C++14

#1064 Document iteration encodings
  docs/source/dev/design.rst
  docs/source/usage/concepts.rst
  src/binding/python/IterationEncoding.cpp
Labels: documentation

#1062 Document openpmd-pipe script
  CMakeLists.txt
  docs/source/utilities/cli.rst
  setup.py
  src/binding/python/openpmd_api/pipe/__init__.py
  src/binding/python/openpmd_api/pipe/__main__.py
  src/cli/pipe.py
Labels: documentation, tools

#1068 Document regexes for showing only attributes or datasets in new ADIOS2 schema
  docs/source/backends/adios2.rst
Labels: affects latest release, backend: ADIOS2, documentation

#1069 Fix: openpmd-pipe --help
  src/binding/python/openpmd_api/pipe/__main__.py
Labels: documentation, tools

#1070 Add CITATION.cff
  CITATION.cff
Labels: documentation

#1058 Release: 0.14.0
  .rodare.json
  CHANGELOG.rst
  CITATION.cff
  NEWS.rst
  README.md
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#1072 Wheels: 0.14.0
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment, frontend: Python3

#1071 Post 0.14.0 Changelog Template
  CHANGELOG.rst
  CITATION.cff
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation
