Repository openPMD/openPMD-api, pull requests merged in 2021-09, with the labels that each got.

#1093 switchType: Do not take action object as argument any more
  include/openPMD/Datatype.hpp
  include/openPMD/DatatypeHelpers.hpp
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/backend/BaseRecordComponent.hpp
  include/openPMD/benchmark/mpi/MPIBenchmark.hpp
  src/Datatype.cpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ADIOS2PreloadAttributes.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/RecordComponent.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
Labels: refactoring, internal

#1100 Remove Datatype::DATATYPE
  include/openPMD/Datatype.hpp
  include/openPMD/DatatypeHelpers.hpp
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/binding/python/Numpy.hpp
  src/Datatype.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5Auxiliary.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/backend/Attributable.cpp
  src/binding/python/Datatype.cpp
Labels: api: breaking, frontend: C++14, frontend: Python3

#1099 RecordComponent::resetDataset(): Reject undefined datatypes
  src/RecordComponent.cpp
Labels: api: breaking, frontend: C++14

#1102 Executables: CXX_STANDARD/EXTENSIONS
  CMakeLists.txt
Labels: bug, affects latest release, install

#1101 Two suggestions to fix CommonADIOS1IOHandlerImpl
  CMakeLists.txt
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/CommonADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
Labels: refactoring, backend: ADIOS1, internal

#1104 Doc: More Locations -DPython_EXECUTABLE
  README.md
  docs/source/install/install.rst
Labels: install, documentation, frontend: Python3

#1105 CMake: Set RPATHs on Installed Targets
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
Labels: install

#1103 NVCC + C++17
  include/openPMD/backend/Attributable.hpp
Labels: workaround

#1111 Lazy parsing: Make findable in docs and use in openpmd-ls
  docs/source/backends/adios2.rst
  docs/source/details/backendconfig.rst
  include/openPMD/cli/ls.hpp
Labels: tools, documentation

#1106 HDF5: Document HDF5_USE_FILE_LOCKING
  docs/source/backends/hdf5.rst
Labels: documentation, backend: HDF5, workaround

#1107 Avoid object slicing when deriving from Series class
  include/openPMD/Series.hpp
  src/Series.cpp
Labels: bug, affects latest release, internal

#1114 Doc: OMPI_MCA_io Control
  docs/source/backends/hdf5.rst
Labels: documentation, backend: HDF5, workaround
