Repository openPMD/openPMD-api, pull requests merged in 2021-01, with the labels that each got.

#862 Iteration::open()
  docs/source/details/mpi.rst
  include/openPMD/Iteration.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/Iteration.cpp
  src/binding/python/Iteration.cpp
  test/ParallelIOTest.cpp
Labels: MPI, api: new, backend: ADIOS2, bug

#861 Release: 0.13.0
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#865 Post 0.13.0 Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#866 Wheels: 0.13.0
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment, frontend: Python3

#869 Docs: Release PyPI Incl. Win
  docs/source/maintenance/release.rst
Labels: documentation

#864 Fix ADIOS1: Iteration::open()
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  test/ParallelIOTest.cpp
Labels: MPI, affects latest release, backend: ADIOS1, bug, help wanted

#872 Wheels: ZFP Static
  library_builders.sh
Labels: bug, continuous deployment

#871 Adapt sourceID test to nondeterministic subfile order
  test/ParallelIOTest.cpp
Labels: MPI, affects latest release, bug, tests

#874 Wheels: 0.13.0.post0
  .github/workflows/build.yml
Labels: continuous deployment

#877 CI: Brew Returns Non-Zero If Already Installed
  .github/workflows/unix.yml
Labels: continuous integration, machine/system, workaround

#873 LGTM: Fix C++
  .lgtm.yml
Labels: continuous integration, third party, workaround

#876 Wheels: 0.13.0.post1
  .github/workflows/build.yml
Labels: continuous deployment

#875 setup.py: stay with Python_EXECUTABLE
  setup.py
Labels: bug, frontend: Python3, install

#878 Ensure that a Series is not dirtyRecursive() after reading
  src/Mesh.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/backend/MeshRecordComponent.cpp
Labels: affects latest release, bug

#879 ChunkInfo: Fix Includes
  include/openPMD/ChunkInfo.hpp
  src/ChunkInfo.cpp
Labels: cosmetic

#881 ADIOS2: Add a Missing Space (Msg)
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: cosmetic

#880 Tests: listSeries Coverage
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: tests

#884 Fix JSON: listSeries
  src/IO/JSON/JSONIOHandlerImpl.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, backend: JSON, bug, help wanted

#868 FindPython.cmake: Development.Module
  CMakeLists.txt
Labels: affects latest release, bug, continuous deployment, frontend: Python3, install

#882 Fix: listSeries & Iteration::close()
  src/Iteration.cpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, help wanted, internal

#883 Fix ADIOS1: listSeries
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, backend: ADIOS1, bug, help wanted

#885 JSON Complex Datatype Read
  src/IO/JSON/JSONIOHandlerImpl.cpp
  test/SerialIOTest.cpp
Labels: backend: JSON, help wanted

#890 Bounds Check: More Readable Error Message
  include/openPMD/RecordComponent.hpp
Labels: cosmetic

#892 Docs: Fix Formatting of First Read/Write
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: affects latest release, bug, documentation

#891 Release: 0.13.1
  CHANGELOG.rst
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#893 Post 0.13.1 Changelog Template
  CHANGELOG.rst
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#894 Wheels: 0.13.1
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment, frontend: Python3

#895 Support Null engine in ADIOS2
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend, backend: ADIOS2

#897 CMake: Prefix Test/CLI/Example Switches
  CMakeLists.txt
  Dockerfile
  README.md
  Singularity
  docs/source/dev/buildoptions.rst
  setup.py
Labels: install

#896 CMake: Hint CMAKE_PREFIX_PATH Warning
  CMakeLists.txt
Labels: documentation, install, warning

#900 CMake: Fix New Prefixes
  CMakeLists.txt
  README.md
Labels: bug, install

#899 Weak scaling in benchmark example
  docs/source/usage/benchmarks.rst
  examples/8_benchmark_parallel.cpp
Labels: MPI, tests

#902 Docs: make clean
  docs/Makefile
Labels: documentation

#908 setup.py: remove duplicate 'YES'
  setup.py
Labels: frontend: Python3, install

#909 Check whether particlePatches are dirty
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  test/SerialIOTest.cpp
Labels: affects latest release, bug, internal

#889 Read JSON options from file
  docs/source/details/backendconfig.rst
  include/openPMD/auxiliary/Filesystem.hpp
  include/openPMD/auxiliary/JSON.hpp
  include/openPMD/auxiliary/StringManip.hpp
  include/openPMD/auxiliary/Unused.hpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/auxiliary/Filesystem.cpp
  src/auxiliary/JSON.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: api: new

#910 CI: Ubuntu-latest -> 20.04
  .github/workflows/source.yml
Labels: continuous integration

#912 Python: store_chunk(temporary)
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: affects latest release, bug, frontend: Python3

#903 Activate streaming examples in CI
  CMakeLists.txt
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  examples/10_streaming_write.cpp
  examples/10_streaming_write.py
  src/config.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: backend: ADIOS2, continuous integration, tests

#915 Python: Complex Types in store_chunk
  src/binding/python/RecordComponent.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, frontend: Python3
