Repository openPMD/openPMD-api, pull requests merged in 2021-04, with the labels that each got.

#938 lazy parsing of iterations
  docs/source/details/backendconfig.rst
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Series.hpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Iteration.cpp
  src/ReadIterations.cpp
  src/Series.cpp
  src/binding/python/Series.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new

#956 DataFrame: Fix unitSI
  src/binding/python/openpmd_api/DataFrame.py
Labels: bug, frontend: Python3

#955 Default constructors for Series and SeriesIterator
  include/openPMD/ReadIterations.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  src/ReadIterations.cpp
  src/Series.cpp
Labels: frontend: C++11

#952 Dask: Array
  README.md
  examples/11_particle_dataframe.py
  src/binding/python/openpmd_api/DaskArray.py
  src/binding/python/openpmd_api/__init__.py
Labels: api: new, frontend: Python3

#958 Dask: 2D Phase Space Example
  examples/11_particle_dataframe.py
Labels: frontend: Python3, tests

#959 DaskDataFrame: Fix Chunks
  src/binding/python/openpmd_api/DaskDataFrame.py
Labels: bug, frontend: Python3

#962 HDF5: Fix Segfault with libSplash Files
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: affects latest release, backend: HDF5, bug

#965 Wheels 0.13.3
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: continuous deployment, frontend: Python3

#901 Expose internal buffers to writers
  CMakeLists.txt
  docs/source/index.rst
  docs/source/usage/examples.rst
  docs/source/usage/workflow.rst
  examples/12_span_write.cpp
  examples/12_span_write.py
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
  include/openPMD/Series.hpp
  include/openPMD/Span.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/PatchRecord.cpp
  src/backend/Writable.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/openpmd_api/pipe/__init__.py
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: api: new, backend, backend: ADIOS2

#966 Retrieve paths of objects in the openPMD hierarchy
  CMakeLists.txt
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/Writable.hpp
  src/Iteration.cpp
  src/ParticleSpecies.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/Container.cpp
  test/CoreTest.cpp
Labels: api: new, frontend: C++11

#970 CI: Brew Update
  .github/workflows/unix.yml
Labels: continuous integration, third party

#855 Step-Based iteration layout
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/IterationEncoding.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/Iteration.cpp
  src/IterationEncoding.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/ReadIterations.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecordComponent.cpp
  src/binding/python/IterationEncoding.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: api: new, backend: ADIOS2
