Repository openPMD/openPMD-api, pull requests merged in 2021-11, with the labels that each got.

#1134 libfabric 1.6+: Document SST Work-Arounds
  docs/source/backends/adios2.rst
Labels: bug, third party, documentation, backend: ADIOS2

#1118 Fix: Read Inconsistent Zero Pads
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, internal

#1136 Wheels: 0.14.3
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1140 Add `cmake/` to MANIFEST.in
  MANIFEST.in
Labels: bug, affects latest release, install, frontend: Python3

#1137 Fix parsing for grid spacing with type long double
  src/Mesh.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, frontend: Python3

#1142 Install pre-commit
  .pre-commit-config.yaml
  conda.yml
  spack.yaml
Labels: tests

#1139 Python: 3.10
  .github/workflows/linux.yml
  Dockerfile
  NEWS.rst
  README.md
  docs/source/dev/dependencies.rst
  setup.py
Labels: frontend: Python3

#1149 Fix: Python Iteration Repr Typo
  src/binding/python/Iteration.cpp
Labels: bug, affects latest release, frontend: Python3
