Repository openPMD/openPMD-api, pull requests merged in 2022-01, with the labels that each got.

#1160 Wheels: Musllinux (Alpine) Support
  .github/workflows/build.yml
  .travis.yml
  library_builders.sh
Labels: frontend: Python3, continuous deployment

#1162 Fix reading of dataset-specific configuration in ADIOS1
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  test/SerialIOTest.cpp
Labels: bug, backend: ADIOS1

#1146 Read backend configuration from .toml files
  CMakeLists.txt
  docs/source/details/adios1.toml
  docs/source/details/adios2.toml
  docs/source/details/backendconfig.rst
  docs/source/details/config_layout.json
  docs/source/details/config_layout.toml
  examples/13_write_dynamic_configuration.cpp
  examples/13_write_dynamic_configuration.py
  include/openPMD/auxiliary/JSON_internal.hpp
  src/Error.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/IOTask.cpp
  src/auxiliary/JSON.cpp
  test/JSONTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: api: new

#1165 CMake 3.22+: Policy CMP0127
  CMakeLists.txt
Labels: warning, install

#1167 ADIOS1: Fix Serial Builds, CI: Clang 10->12
  .github/ci/spack-envs/clang12_py38_nompi_h5_ad1_ad2/spack.yaml
  .github/workflows/linux.yml
  CMakeLists.txt
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
Labels: bug, affects latest release, backend: ADIOS1, continuous integration

#1170 Docs: Minor Warnings
  docs/source/details/mpi.rst
  docs/source/dev/dependencies.rst
Labels: warning, documentation

#1169 Docs: Fix HDF5 JSON File
  docs/source/details/backendconfig.rst
  docs/source/details/hdf5.json
Labels: bug, affects latest release, documentation, backend: HDF5

#1168 Docs: Update Citation & Add BibTeX
  docs/source/citation.rst
Labels: documentation

#1171 Docs: Fix CLI Highlighting
  docs/source/utilities/cli.rst
Labels: warning, documentation

#1172 CMake: Warning Flags First in CXXFLAGS
  CMakeLists.txt
Labels: warning, install

#1175 pre-commit: sort Python includes (PEP8)
  .editorconfig
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/10_streaming_read.py
  examples/10_streaming_write.py
  examples/11_particle_dataframe.py
  examples/12_span_write.py
  examples/13_write_dynamic_configuration.py
  examples/2_read_serial.py
  examples/2a_read_thetaMode_serial.py
  examples/3_write_serial.py
  examples/3a_write_thetaMode_serial.py
  examples/3b_write_resizable_particles.py
  examples/4_read_parallel.py
  examples/5_write_parallel.py
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  setup.py
  src/binding/python/openpmd_api/DaskArray.py
  src/binding/python/openpmd_api/DaskDataFrame.py
  src/binding/python/openpmd_api/DataFrame.py
  src/binding/python/openpmd_api/__init__.py
  src/binding/python/openpmd_api/ls/__main__.py
  src/binding/python/openpmd_api/pipe/__main__.py
  src/cli/pipe.py
  test/python/unittest/API/APITest.py
  test/python/unittest/Test.py
Labels: frontend: Python3, continuous integration

#1166 ADIOS2 fixes: Incompatibilites with current ADIOS2 master branch
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/IOTask.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, backend: ADIOS2

#1178 Pre-Commit: Check Common `.rst` Issues
  .pre-commit-config.yaml
  docs/source/dev/sphinx.rst
  docs/source/maintenance/release.rst
Labels: documentation, continuous integration

#1177 Release 0.14.4 backports
  .github/workflows/linux.yml
  .pre-commit-config.yaml
  CHANGELOG.rst
  CITATION.cff
  CMakeLists.txt
  Dockerfile
  MANIFEST.in
  NEWS.rst
  README.md
  docs/source/citation.rst
  docs/source/conf.py
  docs/source/details/backendconfig.rst
  docs/source/details/hdf5.json
  docs/source/details/mpi.rst
  docs/source/dev/dependencies.rst
  docs/source/index.rst
  docs/source/utilities/cli.rst
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/version.hpp
  setup.py
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/IOTask.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/RecordComponent.cpp
  src/binding/python/Iteration.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release

#1180 Wheels: 0.14.4
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1164 C++17
  .github/ci/spack-envs/clang6_nopy_nompi_h5_libcpp/spack.yaml
  .github/ci/spack-envs/clang6_nopy_ompi_h5_ad1_ad2_bp3_libcpp/spack.yaml
  .github/ci/spack-envs/clang7_nopy_ompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/gcc7_py36_ompi_h5_ad1_ad2/spack.yaml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  CMakeLists.txt
  NEWS.rst
  README.md
  cmake/openPMDFunctions.cmake
  cmake/try_variant.cpp
  docs/source/citation.rst
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
  examples/8a_benchmark_write_parallel.cpp
  include/openPMD/DatatypeHelpers.hpp
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/ReadIterations.hpp
  include/openPMD/Series.hpp
  include/openPMD/WriteIterations.hpp
  include/openPMD/auxiliary/JSON_internal.hpp
  include/openPMD/auxiliary/Option.hpp
  include/openPMD/auxiliary/Unused.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/auxiliary/VariantSrc.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/binding/python/Numpy.hpp
  include/openPMD/binding/python/Variant.hpp
  include/openPMD/openPMD.hpp
  openPMDConfig.cmake.in
  share/openPMD/thirdParty/variant/include/mpark/variant.hpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ADIOS2PreloadAttributes.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/ReadIterations.cpp
  src/Series.cpp
  src/WriteIterations.cpp
  src/auxiliary/Date.cpp
  src/auxiliary/Filesystem.cpp
  src/auxiliary/JSON.cpp
  src/backend/Container.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/RecordComponent.cpp
  src/helper/list_series.cpp
  test/AuxiliaryTest.cpp
  test/JSONTest.cpp
  test/SerialIOTest.cpp
Labels: api: breaking

#1184 Fix Attribute constructor error on NVCC
  include/openPMD/backend/Attribute.hpp
Labels: bug, workaround

#1183 Avoid SFINAE in Attribute conversion
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/auxiliary/TypeTraits.hpp
  include/openPMD/backend/Attribute.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: refactoring, internal

#1185 C++17: Remove Earlier EDG Attribute Work-Arounds
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Attribute.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/RecordComponent.cpp
  test/CoreTest.cpp
Labels: refactoring, workaround
