Repository openPMD/openPMD-api, pull requests merged in 2022-06, with the labels that each got.

#1286 Wheels: 0.14.5
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1288 ADIOS1: Link Own `IOTask.cpp`
  CMakeLists.txt
Labels: bug, affects latest release, backend: ADIOS1

#1275 Distinguish all char types in ADIOS2 backend
  include/openPMD/Datatype.hpp
  include/openPMD/DatatypeHelpers.hpp
  include/openPMD/Datatype_internal.hpp
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2PreloadAttributes.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/backend/Attribute.hpp
  include/openPMD/binding/python/Numpy.hpp
  src/Datatype.cpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5Auxiliary.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/RecordComponent.cpp
  src/backend/Attributable.cpp
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/RecordComponent.cpp
  test/SerialIOTest.cpp
Labels: bug, backend: ADIOS2
