Repository openPMD/openPMD-api, pull requests merged in 2022-11, with the labels that each got.

#1278 Add Attribute::getOptional<T>() and use to add some more dynamic datatype conversions at read time
  include/openPMD/backend/Attribute.hpp
  include/openPMD/backend/BaseRecord.hpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  test/SerialIOTest.cpp
Labels: api: breaking, internal, api: new

#1323 Python 3.11
  .github/ci/spack-envs/clang14_py311_nompi_h5_ad1_ad2/spack.yaml
  .github/workflows/linux.yml
  CHANGELOG.rst
  CMakeLists.txt
  Dockerfile
  NEWS.rst
  README.md
  conda.yml
  docs/source/dev/dependencies.rst
  setup.py
  src/IO/HDF5/HDF5Auxiliary.cpp
Labels: frontend: Python3

#1325 Docs: Recommend Static Build for Superbuilds
  README.md
Labels: documentation

#1327 Variant constructor: Treat as explicit
  include/openPMD/backend/Attribute.hpp
Labels: bug, workaround

#1285 Add IterationIndex_t to replace hardcoded uint64_t to index iterations
  include/openPMD/Iteration.hpp
  include/openPMD/Series.hpp
  include/openPMD/WriteIterations.hpp
  include/openPMD/benchmark/mpi/MPIBenchmark.hpp
  include/openPMD/benchmark/mpi/MPIBenchmarkReport.hpp
  src/Iteration.cpp
  src/Series.cpp
  src/WriteIterations.cpp
  src/binding/python/Container.cpp
  src/binding/python/Series.cpp
Labels: frontend: C++17
