Repository openPMD/openPMD-api, pull requests merged in 2022-05, with the labels that each got.

#1246 CI: No Need for Warn Deprecations
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/nvidia.yml
  .github/workflows/tooling.yml
Labels: warning, continuous integration

#1267 Fix code line numbers in design.rst that include the Operation enum
  docs/source/dev/design.rst
Labels: documentation

#1262 BP5 tests: Only run them if ADIOS2 has BP5
  .appveyor.yml
  test/SerialIOTest.cpp
Labels: tests, backend: ADIOS2, continuous integration

#1239 Fixes for opening an iteration
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/Iteration.cpp
  src/ReadIterations.cpp
  src/Series.cpp
  src/WriteIterations.cpp
  src/backend/Attributable.cpp
  src/backend/Writable.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, internal

#1268 Avoid copying std::string in for loop
  src/IO/IOTask.cpp
Labels: warning

#1264 Fix premature flushing (performance bug)
  CMakeLists.txt
  docs/source/dev/design.rst
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/Mesh.cpp
  src/Record.cpp
  src/Series.cpp
Labels: bug, internal

#1269 Remove deprecated debug parameter in ADIOS2
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2

#1007 ADIOS2 Append Mode
  docs/source/usage/workflow.rst
  include/openPMD/Error.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/Access.hpp
  src/Error.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/PatchRecordComponent.cpp
  src/binding/python/Error.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2

#1271 CI: ADIOS 2.7.1
  .github/ci/spack-envs/clang8_py38_mpich_h5_ad1_ad2/spack.yaml
  .github/workflows/linux.yml
Labels: backend: ADIOS2, continuous integration

#1272 CI: Expand Read-Only Permission Tests
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/nvidia.yml
  .github/workflows/tooling.yml
  share/openPMD/download_samples.sh
Labels: continuous integration

#1281 Wheels win32
  .github/workflows/build.yml
Labels: continuous deployment
