Repository openPMD/openPMD-api, pull requests merged in 2022-03, with the labels that each got.

#1220 pybind11: v2.9.1+
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  share/openPMD/thirdParty/pybind11/CMakeLists.txt
  share/openPMD/thirdParty/pybind11/README.rst
  share/openPMD/thirdParty/pybind11/include/pybind11/attr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/buffer_info.h
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/chrono.h
  share/openPMD/thirdParty/pybind11/include/pybind11/complex.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/descr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/init.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/type_caster_base.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/typeid.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen.h
  share/openPMD/thirdParty/pybind11/include/pybind11/embed.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eval.h
  share/openPMD/thirdParty/pybind11/include/pybind11/functional.h
  share/openPMD/thirdParty/pybind11/include/pybind11/gil.h
  share/openPMD/thirdParty/pybind11/include/pybind11/iostream.h
  share/openPMD/thirdParty/pybind11/include/pybind11/numpy.h
  share/openPMD/thirdParty/pybind11/include/pybind11/operators.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl/filesystem.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/pybind11/__init__.py
  share/openPMD/thirdParty/pybind11/pybind11/__main__.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.pyi
  share/openPMD/thirdParty/pybind11/pybind11/commands.py
  share/openPMD/thirdParty/pybind11/pybind11/setup_helpers.py
  share/openPMD/thirdParty/pybind11/pybind11/setup_helpers.pyi
  share/openPMD/thirdParty/pybind11/tools/check-style.sh
  share/openPMD/thirdParty/pybind11/tools/libsize.py
  share/openPMD/thirdParty/pybind11/tools/make_changelog.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Common.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Config.cmake.in
  share/openPMD/thirdParty/pybind11/tools/pybind11NewTools.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
  share/openPMD/thirdParty/pybind11/tools/setup_global.py.in
  share/openPMD/thirdParty/pybind11/tools/setup_main.py.in
Labels: third party, frontend: Python3

#1219 Python: Do Not Strip Symbols In Debug
  CMakeLists.txt
Labels: bug, affects latest release, install, frontend: Python3

#1222 Clang-Format 13: JSON
  .clang-format
  .github/workflows/clang-format/clang-format.sh
  .pre-commit-config.yaml
  .rodare.json
  docs/source/details/adios2.json
  docs/source/details/config_layout.json
Labels: continuous integration

#1224 Fix use after free in ADIOS1IOHandler
  include/openPMD/IO/ADIOS/CommonADIOS1IOHandler.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
Labels: bug, affects latest release, backend: ADIOS1

#1226 Pass-through flushing parameters
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/DummyIOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/Mesh.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/Record.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
  include/openPMD/Series.hpp
  include/openPMD/Span.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/backend/Container.hpp
  include/openPMD/backend/PatchRecord.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/DummyIOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandler.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/Attributable.cpp
  src/backend/BaseRecordComponent.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecord.cpp
  src/backend/PatchRecordComponent.cpp
  src/backend/Writable.cpp
Labels: refactoring

#1223 Don't safeguard empty strings while reading
  include/openPMD/backend/Attributable.hpp
  src/backend/Attributable.cpp
Labels: bug, affects latest release, backend: ADIOS2, internal, workaround

#1235 Add memory leak suppression: ps_make_timer_name_
  .github/ci/sanitizer/clang/Leak.supp
Labels: backend: ADIOS2, continuous integration

#1214 Clearly fail when users select a wrong backend
  src/IO/AbstractIOHandlerHelper.cpp
  test/CoreTest.cpp
Labels: bug, affects latest release, backend: HDF5, backend: ADIOS1, backend: ADIOS2

#1236 Fix: Missing HDF5 Include
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: bug, affects latest release, backend: HDF5
