Repository openPMD/openPMD-api, pull requests merged in 2022-04, with the labels that each got.

#1241 CI: NVHPC New Apt Repo
  .github/workflows/dependencies/install_nvhpc21-11.sh
  .github/workflows/nvidia.yml
Labels: bug, tests, third party

#1225 Increase reference count also in other load_chunk overload
  src/binding/python/RecordComponent.cpp
Labels: bug, affects latest release, frontend: Python3

#1244 CI: Fix Spack
  .github/ci/spack-envs/clang12_py38_nompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/clang6_nopy_nompi_h5_libcpp/spack.yaml
  .github/ci/spack-envs/clang6_nopy_ompi_h5_ad1_ad2_bp3_libcpp/spack.yaml
  .github/ci/spack-envs/clang7_nopy_ompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/clang8_py38_mpich_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/clangtidy_nopy_ompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack-envs/gcc7_py36_ompi_h5_ad1_ad2/spack.yaml
  .github/ci/spack/compilers.yaml
  .github/ci/spack/config.yaml
  .github/ci/spack/packages.yaml
  .github/workflows/dependencies/install_spack
  .github/workflows/linux.yml
Labels: bug, third party, continuous integration

#1240 use CUDA ptrs in 8a when it is enabled
  CMakeLists.txt
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  examples/8a_benchmark_write_parallel.cpp
  include/openPMD/config.hpp.in
Labels: tests, backend: ADIOS2

#1215 Fixes for BP5 engine
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, backend: ADIOS2

#1213 Fix GCC 11 Compiler Warnings
  include/openPMD/backend/Attribute.hpp
  test/SerialIOTest.cpp
Labels: warning, cosmetic, internal

#1242 Python Iteration: Fix __repr__ (time)
  src/binding/python/Iteration.cpp
Labels: bug, affects latest release, frontend: Python3

#1251 Fix: Unused Lambda in SerialIOTest
  test/SerialIOTest.cpp
Labels: warning

#1255 SerialIOTest: Fix GCC Pragma Check
  test/SerialIOTest.cpp
Labels: warning

#1254 Doc: Iterate Loop reference
  README.md
Labels: documentation, frontend: C++14

#1256 CI: Update CUDA repo key
  .github/workflows/dependencies/install_nvcc11.sh
Labels: third party, continuous integration

#1259 Revert SerialIOTest: Fix GCC Pragma Check
  test/SerialIOTest.cpp
Labels: bug

#1261 CI: Fix Conda Build - <3 Mamba
  .github/workflows/linux.yml
Labels: bug, continuous integration

#1260 SerialIOTest: Fix GCC Pragma Check
  test/SerialIOTest.cpp
Labels: warning

#1253 Fix Zero Pattern Issue
  include/openPMD/Iteration.hpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: bug, help wanted, affects latest release, internal

#1250 Doc: Update HDF5 Coll. Metadata Versions
  docs/source/backends/hdf5.rst
Labels: documentation, backend: HDF5
