Repository openPMD/openPMD-api, pull requests merged in 2022-08, with the labels that each got.

#1303 Fix file existence check in parallel tests
  test/ParallelIOTest.cpp
Labels: bug, tests

#1218 ADIOS2: more fine-grained control for file endings
  docs/source/backends/adios2.rst
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/IO/Format.hpp
  include/openPMD/Series.hpp
  src/Format.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Series.cpp
  src/config.cpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: backend: ADIOS2

#1309 Fix `operationAsString` Export
  include/openPMD/IO/IOTask.hpp
Labels: bug, affects latest release, backend: ADIOS1

#1296 storeChunk: Add an overload for shared_ptr<T[]>
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
Labels: frontend: C++14, api: new
