Repository openPMD/openPMD-api, pull requests merged in 2022-12, with the labels that each got.

#1344 Catch2 v2.13.10
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  share/openPMD/thirdParty/catch2/include/catch2/catch.hpp
Labels: tests, third party

#1346 CI: Style w/ Ubuntu 22.04
  .github/workflows/source.yml
Labels: documentation, continuous integration

#1341 Docs: Latest Sphinx, Docutils, RTD
  .readthedocs.yml
  docs/requirements.txt
  docs/source/index.rst
Labels: documentation

#1326 CMake: Fix Build & Install Option Names
  CMakeLists.txt
  cmake/openPMDFunctions.cmake
Labels: bug, affects latest release, install

#1340 Prefer parallel HDF5 in find_package in downstream use
  .rodare.json
  CHANGELOG.rst
  README.md
  openPMDConfig.cmake.in
Labels: bug, affects latest release, install, backend: HDF5, MPI

#1324 Add Series::close() call
  examples/2_read_serial.cpp
  examples/2_read_serial.py
  examples/2a_read_thetaMode_serial.cpp
  examples/2a_read_thetaMode_serial.py
  examples/3_write_serial.cpp
  examples/3_write_serial.py
  examples/3a_write_thetaMode_serial.cpp
  examples/3a_write_thetaMode_serial.py
  examples/3b_write_resizable_particles.cpp
  examples/3b_write_resizable_particles.py
  examples/4_read_parallel.cpp
  examples/4_read_parallel.py
  examples/5_write_parallel.cpp
  examples/5_write_parallel.py
  examples/6_dump_filebased_series.cpp
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Series.cpp
  src/binding/python/Series.cpp
  test/AuxiliaryTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: frontend: C++17, frontend: Python3, api: new

#1348 Python Tests: Fix `long` Numpy Type
  test/python/unittest/API/APITest.py
Labels: bug, tests, affects latest release, frontend: Python3

#1336 Add switches --mpi and --no-mpi to openpmd-pipe
  src/binding/python/openpmd_api/pipe/__main__.py
Labels: tools, MPI

#1337 Document why m_backendAccess and m_frontendAccess are distinguished
  include/openPMD/IO/AbstractIOHandler.hpp
Labels: documentation, internal

#1290 Python: grid_spacing & time_offset `double`
  src/binding/python/Mesh.cpp
Labels: bug, affects latest release, frontend: Python3
