Repository openPMD/openPMD-api, pull requests merged in 2023-05, with the labels that each got.

#1438 Update .readthedocs.yml
  .readthedocs.yml
Labels: bug, affects latest release, third party, documentation, continuous integration

#1435 Fix deprecated APIs in first read/write examples
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: documentation

#1446 CI: macOS-11 Update
  .github/workflows/macos.yml
Labels: continuous integration

#1442 Use lazy imports for dask and pandas
  src/binding/python/openpmd_api/DaskArray.py
  src/binding/python/openpmd_api/DaskDataFrame.py
  src/binding/python/openpmd_api/DataFrame.py
Labels: frontend: Python3

#1452 Python: Better error message when loading to a buffer with mismatched type
  src/binding/python/RecordComponent.cpp
Labels: bug, affects latest release, frontend: Python3

#1451 Remove schema 2021 from documentation
  docs/source/backends/adios2.rst
Labels: documentation, backend: ADIOS2
