Repository openPMD/openPMD-api, pull requests merged in 2023-12, with the labels that each got.

#1560 Remove `FindADIOS.cmake`
  Singularity
  docs/Doxyfile
  docs/source/analysis/paraview.rst
  docs/source/dev/dependencies.rst
  examples/8a_benchmark_write_parallel.cpp
  examples/8b_benchmark_read_parallel.cpp
  openPMDConfig.cmake.in
  setup.py
  share/openPMD/cmake/FindADIOS.cmake
  test/SerialIOTest.cpp
Labels: backend: ADIOS1

#1542 ADIOS2: Optionally write attributes only from given ranks
  docs/source/backends/adios2.rst
  docs/source/details/adios2.json
  docs/source/details/adios2.toml
  docs/source/details/backendconfig.rst
  docs/source/details/mpi.rst
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/ParallelIOTest.cpp
Labels: backend: ADIOS2, MPI

#1565 Workaround for current CI issues with clang14 on MacOS
  .github/workflows/macos.yml
  .github/workflows/mpirun_workaround.sh
Labels: continuous integration, workaround

#1566 Docs: Research Groups of Maintainers
  .rodare.json
  CITATION.cff
  README.md
  docs/source/citation.rst
Labels: documentation

#1517 CI: Linux aarch64/arm64
  .circleci/config.yml
  .github/ci/spack-envs/gcc_py_ompi_h5_ad2_arm64/spack.yaml
  include/openPMD/binding/python/Numpy.hpp
  src/binding/python/Attributable.cpp
  test/python/unittest/API/APITest.py
Labels: bug, affects latest release, machine/system, continuous integration

#1573 Partially revert #1368
  src/Series.cpp
Labels: warning, internal, workaround

#1574 Update for OPENPMD_VERBOSE logging
  include/openPMD/IO/IOTask.hpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/backend/Writable.cpp
Labels: bug, warning, internal

#1544 Add visit-like pattern for RecordComponent
  examples/10_streaming_read.cpp
  examples/2_read_serial.cpp
  examples/4_read_parallel.cpp
  include/openPMD/Datatype.hpp
  include/openPMD/Datatype.tpp
  include/openPMD/DatatypeMacros.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
  include/openPMD/auxiliary/TypeTraits.hpp
  include/openPMD/auxiliary/Variant.hpp
  include/openPMD/backend/Attribute.hpp
  src/RecordComponent.cpp
  test/SerialIOTest.cpp
Labels: frontend: C++17, api: new

#1498 Adios2 warn groupbased encoding
  CMakeLists.txt
  docs/source/backends/adios2.rst
  docs/source/details/backendconfig.rst
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/IOTask.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/ReadIterations.cpp
  src/Series.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: warning, api: breaking, backend: ADIOS2

#1578 Add documentation for typical use cases of openpmd-pipe
  docs/source/utilities/cli.rst
Labels: tools, documentation

#1582 Remove constexpr from RecordComponent::visit()
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
Labels: bug, frontend: C++17
