Repository openPMD/openPMD-api, pull requests merged in 2023-04, with the labels that each got.

#1412 Docs: Update Funding
  .rodare.json
  README.md
  docs/source/index.rst
Labels: documentation

#1403 Enable clang-format also for .tpp files by using a regex instead of a predefined filter
  .pre-commit-config.yaml
  include/openPMD/RecordComponent.tpp
  include/openPMD/config.hpp.in
Labels: continuous integration

#1413 Doc: More HTML Updates (CSS)
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
Labels: bug, affects latest release, documentation

#1414 Release 0.15.1
  .github/workflows/windows.yml
  CHANGELOG.rst
  CITATION.cff
  CMakeLists.txt
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  test/SerialIOTest.cpp
Labels: bug, affects latest release, install, documentation, backend: ADIOS1, continuous integration

#1415 Wheels: 0.15.1
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1417 `version.hpp`: 0.15.1
  include/openPMD/version.hpp
Labels: bug, affects latest release

#1421 GitHub Actions: macOS has 3 Cores
  .github/workflows/macos.yml
Labels: continuous integration

#1420 Post 0.15.0 Changelog Template
  .github/workflows/windows.yml
  CHANGELOG.rst
  CITATION.cff
  CMakeLists.txt
  docs/source/conf.py
  include/openPMD/version.hpp
  setup.py
  test/SerialIOTest.cpp
Labels: documentation

#1419 Remove ADIOS1 - Long Live ADIOS2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ci/sanitizer/clang/Leak.supp
  .github/ci/spack-envs/clang14_py311_nompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/clang7_nopy_ompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/clang7_nopy_ompi_h5_ad2_libcpp/spack.yaml
  .github/ci/spack-envs/clang8_py38_mpich_h5_ad2/spack.yaml
  .github/ci/spack-envs/clangtidy_nopy_ompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/gcc7_py36_ompi_h5_ad2/spack.yaml
  .github/workflows/codeql.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/tooling.yml
  CMakeLists.txt
  Dockerfile
  NEWS.rst
  README.md
  docs/source/backends/adios1.rst
  docs/source/backends/adios2.rst
  docs/source/backends/overview.rst
  docs/source/details/adios1.json
  docs/source/details/adios1.toml
  docs/source/details/backendconfig.rst
  docs/source/details/config_layout.json
  docs/source/details/config_layout.toml
  docs/source/details/mpi.rst
  docs/source/dev/buildoptions.rst
  docs/source/index.rst
  docs/source/install/install.rst
  docs/source/usage/firstread.rst
  docs/source/usage/firstwrite.rst
  docs/source/usage/workflow.rst
  examples/8_benchmark_parallel.cpp
  include/openPMD/Error.hpp
  include/openPMD/IO/ADIOS/ADIOS1Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS1FilePosition.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/ADIOS/CommonADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandler.hpp
  include/openPMD/IO/ADIOS/ParallelADIOS1IOHandlerImpl.hpp
  include/openPMD/IO/Format.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/ThrowError.hpp
  include/openPMD/backend/Writable.hpp
  include/openPMD/config.hpp.in
  src/Format.cpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Iteration.cpp
  src/Series.cpp
  src/auxiliary/JSON.cpp
  src/config.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: backend: ADIOS1

#1316 RecordComponent: Properly handle uninitialized datasets
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  include/openPMD/RecordComponent.tpp
  include/openPMD/backend/BaseRecordComponent.hpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/RecordComponent.cpp
  src/backend/BaseRecordComponent.cpp
  src/backend/PatchRecordComponent.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: cosmetic, internal

#1381 Python bindings: Release GIL during IO wait operations
  include/openPMD/Iteration.hpp
  include/openPMD/ReadIterations.hpp
  include/openPMD/WriteIterations.hpp
  src/WriteIterations.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Series.cpp
Labels: frontend: Python3

#1429 Fix gcc9 warning
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
Labels: warning, backend: ADIOS2, internal

#1430 More careful documentation of streaming API
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  examples/10_streaming_write.cpp
  examples/10_streaming_write.py
  examples/12_span_write.cpp
  examples/12_span_write.py
  examples/13_write_dynamic_configuration.cpp
  examples/13_write_dynamic_configuration.py
  examples/1_structure.cpp
  examples/3_write_serial.cpp
  examples/3_write_serial.py
  examples/3a_write_thetaMode_serial.cpp
  examples/3a_write_thetaMode_serial.py
  examples/3b_write_resizable_particles.cpp
  examples/3b_write_resizable_particles.py
  examples/5_write_parallel.cpp
  examples/5_write_parallel.py
  examples/8a_benchmark_write_parallel.cpp
  examples/8b_benchmark_read_parallel.cpp
  include/openPMD/Series.hpp
  include/openPMD/WriteIterations.hpp
  src/binding/python/Series.cpp
Labels: documentation
