Repository openPMD/openPMD-api, pull requests merged in 2023-10, with the labels that each got.

#1533 Bug fix: Linear read mode cannot directly access specific file of file-based Series
  CMakeLists.txt
  src/ReadIterations.cpp
Labels: bug

#1530 openpmd-pipe: fix handling of constant components
  src/binding/python/openpmd_api/pipe/__main__.py
Labels: bug, tools

#1508 Python 3.12: Remove Distutils
  README.md
  docs/source/install/install.rst
  pyproject.toml
  setup.py
Labels: install, refactoring, frontend: Python3

#1535 Fix double mesh.read() call in parsing procedures
  src/Iteration.cpp
Labels: bug, affects latest release, internal

#1541 Sphinx: Limit <7.2
  docs/requirements.txt
  docs/source/conf.py
Labels: bug, affects latest release, third party, documentation

#1539 Doc: Citation More Authors
  docs/source/citation.rst
Labels: documentation

#1543 Wheels: Python 3.12
  .github/workflows/build.yml
  .travis.yml
  library_builders.sh
Labels: frontend: Python3, continuous deployment

#1547 Python: Fix Init Order
  CMakeLists.txt
  include/openPMD/binding/python/Container.H
  src/binding/python/BaseRecord.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/Helper.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/PatchRecord.cpp
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/openPMD.cpp
Labels: bug, affects latest release, frontend: Python3
