Repository openPMD/openPMD-api, pull requests merged in 2023-08, with the labels that each got.

#1489 Update Pybind to 2.11.1
  CHANGELOG.rst
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  share/openPMD/thirdParty/pybind11/CMakeLists.txt
  share/openPMD/thirdParty/pybind11/MANIFEST.in
  share/openPMD/thirdParty/pybind11/README.rst
  share/openPMD/thirdParty/pybind11/include/pybind11/attr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/buffer_info.h
  share/openPMD/thirdParty/pybind11/include/pybind11/cast.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/class.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/descr.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/init.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/internals.h
  share/openPMD/thirdParty/pybind11/include/pybind11/detail/type_caster_base.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen/common.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen/matrix.h
  share/openPMD/thirdParty/pybind11/include/pybind11/eigen/tensor.h
  share/openPMD/thirdParty/pybind11/include/pybind11/embed.h
  share/openPMD/thirdParty/pybind11/include/pybind11/functional.h
  share/openPMD/thirdParty/pybind11/include/pybind11/gil.h
  share/openPMD/thirdParty/pybind11/include/pybind11/numpy.h
  share/openPMD/thirdParty/pybind11/include/pybind11/options.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pybind11.h
  share/openPMD/thirdParty/pybind11/include/pybind11/pytypes.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl.h
  share/openPMD/thirdParty/pybind11/include/pybind11/stl_bind.h
  share/openPMD/thirdParty/pybind11/include/pybind11/type_caster_pyobject_ptr.h
  share/openPMD/thirdParty/pybind11/pybind11/__init__.py
  share/openPMD/thirdParty/pybind11/pybind11/__main__.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.py
  share/openPMD/thirdParty/pybind11/pybind11/_version.pyi
  share/openPMD/thirdParty/pybind11/pybind11/commands.py
  share/openPMD/thirdParty/pybind11/pybind11/setup_helpers.py
  share/openPMD/thirdParty/pybind11/pybind11/setup_helpers.pyi
  share/openPMD/thirdParty/pybind11/tools/FindCatch.cmake
  share/openPMD/thirdParty/pybind11/tools/FindPythonLibsNew.cmake
  share/openPMD/thirdParty/pybind11/tools/codespell_ignore_lines_from_errors.py
  share/openPMD/thirdParty/pybind11/tools/make_changelog.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Common.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Config.cmake.in
  share/openPMD/thirdParty/pybind11/tools/pybind11NewTools.cmake
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
  share/openPMD/thirdParty/pybind11/tools/setup_global.py.in
  share/openPMD/thirdParty/pybind11/tools/setup_main.py.in
Labels: third party, frontend: Python3

#1310 ADIOS2 schema 2022_07_26, based on ADIOS2 modifiable attributes
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  CMakeLists.txt
  docs/source/backends/adios2.rst
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2FilePosition.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/ADIOS2PreloadAttributes.hpp
  include/openPMD/IO/ADIOS/macros.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/ADIOS2PreloadAttributes.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2

#1486 CI: macOS 11.0+
  .github/workflows/macos.yml
Labels: continuous integration

#1469 HDF5: Handle unknown datatypes in datasets
  share/openPMD/download_samples.ps1
  share/openPMD/download_samples.sh
  src/IO/HDF5/HDF5IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: HDF5

#1497 Warn on BP5+Blosc in ADIOS2 v2.9 up to patch level 1
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: warning, backend: ADIOS2

#1484 Fixes for variable-based encoding in backends without step support
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/ReadIterations.hpp
  include/openPMD/Series.hpp
  src/IO/AbstractIOHandler.cpp
  src/Iteration.cpp
  src/ReadIterations.cpp
  src/Series.cpp
  src/WriteIterations.cpp
  src/binding/python/Series.cpp
  src/binding/python/openpmd_api/pipe/__main__.py
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, api: new

#1496 CMake: Warnings on AppleClang
  CMakeLists.txt
Labels: warning, install

#1501 Pandas DataFrames: Add Row Column Name
  src/binding/python/openpmd_api/DaskDataFrame.py
  src/binding/python/openpmd_api/DataFrame.py
Labels: bug, third party, documentation

#1503 ADIOS 2.9: Avoid Unused Param Warning
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: warning, backend: ADIOS2

#1502 Python: 3.8+
  CMakeLists.txt
  Dockerfile
  README.md
  conda.yml
  docs/source/dev/dependencies.rst
  setup.py
Labels: install, documentation, frontend: Python3

#1495 Optional debugging output for AbstractIOHandlerImpl::flush()
  docs/source/usage/workflow.rst
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  src/IO/AbstractIOHandlerImpl.cpp
Labels: internal

#1387 Wheels: ADIOS2 -> v2.9.0, blosc2
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: backend: ADIOS2, continuous deployment

#1477 make it possible to manually set chunks when loading dask arrays
  docs/source/analysis/dask.rst
  src/binding/python/openpmd_api/DaskArray.py
Labels: frontend: Python3, api: new

#1436 TOML Backend
  docs/source/backends/json.rst
  include/openPMD/IO/Format.hpp
  include/openPMD/IO/JSON/JSONIOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/auxiliary/TypeTraits.hpp
  src/Format.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/JSON/JSONIOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Series.cpp
  src/auxiliary/JSON.cpp
  src/config.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
  test/python/unittest/API/APITest.py
Labels: backend, backend: TOML

#1511 Streaming examples: Set WAN as default transport
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  examples/10_streaming_write.cpp
  examples/10_streaming_write.py
Labels: MPI, continuous integration

#1509 Replace openPMD_Datatypes global with function
  include/openPMD/Datatype.hpp
  src/Datatype.cpp
Labels: bug, affects latest release, api: breaking

#1510 Docs: Fix records length in "9_particle_write_serial.py"
  examples/9_particle_write_serial.py
Labels: tests, documentation, frontend: Python3

#1521 Python: Fix ODR Violation
  include/openPMD/binding/python/Common.hpp
  include/openPMD/binding/python/Numpy.hpp
  include/openPMD/binding/python/Pickle.hpp
  src/binding/python/Access.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/BaseRecord.cpp
  src/binding/python/BaseRecordComponent.cpp
  src/binding/python/ChunkInfo.cpp
  src/binding/python/Container.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Datatype.cpp
  src/binding/python/Error.cpp
  src/binding/python/Helper.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/IterationEncoding.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/PatchRecord.cpp
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  src/binding/python/UnitDimension.cpp
  src/binding/python/openPMD.cpp
Labels: bug, affects latest release, frontend: Python3

#1519 CI: Old CTest
  .github/workflows/linux.yml
Labels: bug, tests, affects latest release, continuous integration

#1518 Fix `chmod` in `download_samples.sh`
  share/openPMD/download_samples.sh
Labels: bug, tests, tools, affects latest release

#1520 Fix CMake: HDF5 Libs are PUBLIC
  CMakeLists.txt
Labels: bug, affects latest release, install, backend: HDF5

#1515 Wheels: 0.15.2
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: frontend: Python3, continuous deployment
