Repository openPMD/openPMD-api, pull requests merged in 2023-03, with the labels that each got.

#1386 Close HFD5 handles in availableChunks task
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: bug, affects latest release, backend: HDF5

#1378 Some fixes for char signs
  include/openPMD/binding/python/Numpy.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: bug, affects latest release, backend: HDF5, frontend: Python3

#1384 CMake: Multi-Config Generator
  CMakeLists.txt
Labels: bug, tests, install

#1391 Release: 0.15.0
  CHANGELOG.rst
  CITATION.cff
  NEWS.rst
  docs/source/conf.py
  docs/source/index.rst
  include/openPMD/version.hpp
  setup.py
Labels: documentation

#1393 CMake: Fix Python Install Directory
  CMakeLists.txt
  setup.py
Labels: bug, affects latest release, install

#1395 macOS AppleClang12 Fixes
  .github/workflows/macos.yml
  include/openPMD/RecordComponent.tpp
  include/openPMD/backend/PatchRecordComponent.hpp
Labels: bug, affects latest release

#1392 Wheels: 0.15.0
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1399 Docs: Formatting of Lists in 0.15.0
  CHANGELOG.rst
Labels: documentation

#1400 Fix: Artifact Placement in Windows Wheels
  .github/workflows/windows.yml
  CMakeLists.txt
  setup.py
Labels: bug, affects latest release, install, frontend: Python3

#1394 Releases: Nils Schild (IPP)
  .rodare.json
  README.md
Labels: documentation

#1401 Wheels: 0.15.0.post1
  .github/workflows/build.yml
  .travis.yml
Labels: frontend: Python3, continuous deployment

#1398 Docs: ADIOS1 EOL in Overview
  docs/source/backends/adios2.rst
  docs/source/backends/overview.rst
Labels: documentation, backend: ADIOS1, backend: ADIOS2

#1404 Fix docs post 0.15
  docs/source/backends/adios2.rst
  docs/source/details/adios1.json
  docs/source/details/adios1.toml
Labels: documentation

#1402 README: Remove LGTM Batches
  README.md
Labels: documentation

#1407 Fix Missing ADIOS1 Stubs in Library
  CMakeLists.txt
Labels: bug, affects latest release, backend: ADIOS1, continuous integration

#1409 Work-Around: libc++ shared_ptr array
  include/openPMD/RecordComponent.tpp
  include/openPMD/backend/PatchRecordComponent.hpp
Labels: bug, affects latest release, install, workaround

#1408 CI: Test on Ubuntu 20.04
  .github/ci/spack-envs/clang7_nopy_nompi_h5_libcpp/spack.yaml
  .github/ci/spack-envs/clang7_nopy_ompi_h5_ad1_ad2_bp3_libcpp/spack.yaml
  .github/ci/spack-envs/gcc7_py36_ompi_h5_ad1_ad2/spack.yaml
  .github/workflows/linux.yml
Labels: continuous integration

#1396 ADIOS1 on macOS
  .github/workflows/macos.yml
  CMakeLists.txt
  include/openPMD/Error.hpp
  include/openPMD/auxiliary/JSON_internal.hpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/IOTask.cpp
  src/auxiliary/JSON.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, install, backend: ADIOS1

#1410 CMake 3.24+: ZLIB_USE_STATIC_LIBS
  Dockerfile
Labels: install, backend: HDF5, backend: ADIOS2, dependencies

#1406 Wheels: 0.15.0.post2
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: frontend: Python3, continuous deployment

#1411 Instantiate only parallel ADIOS1 IO Handler in parallel ADIOS1 library
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
Labels: bug, affects latest release, backend: ADIOS1
