Repository openPMD/openPMD-api, pull requests merged in 2023-06, with the labels that each got.

#1441 Document OpenMPI-ROMIO/HDF5/Chunking issue
  docs/source/backends/hdf5.rst
Labels: documentation, backend: HDF5

#1427 Doc: HDF5_DO_MPI_FILE_SYNC
  docs/source/backends/hdf5.rst
Labels: documentation, backend: HDF5

#1459 openpmd-pipe: set correct install permissions
  CMakeLists.txt
Labels: bug, tools, affects latest release, frontend: Python3

#1440 Fix small documentation issues after 0.15 release
  docs/source/backends/adios2.rst
  docs/source/usage/workflow.rst
Labels: bug, affects latest release, documentation

#1433 HDF5: Fix Char Type Matching
  include/openPMD/Datatype.hpp
  include/openPMD/Datatype.tpp
  include/openPMD/DatatypeHelpers.hpp
  include/openPMD/RecordComponent.tpp
  src/IO/HDF5/HDF5Auxiliary.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, backend: HDF5

#1461 Doc: Sphinx Copybutton and Design
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#1460 added async write flag for ADIOS2
  docs/source/backends/adios2.rst
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2

#1444 Docs: Analysis
  docs/source/analysis/contrib.rst
  docs/source/analysis/dask.rst
  docs/source/analysis/pandas.rst
  docs/source/analysis/paraview.rst
  docs/source/analysis/rapids.rst
  docs/source/analysis/viewer.rst
  docs/source/index.rst
Labels: documentation

#1470 Don't require unitSI when reading a patch record component
  src/backend/PatchRecordComponent.cpp
Labels: bug, affects latest release, internal
