Repository openPMD/openPMD-api, pull requests merged in 2023-07, with the labels that each got.

#1478 CI: oneAPI 2023.2.0
  .github/workflows/dependencies/install_icc
  .github/workflows/dependencies/install_icx
Labels: continuous integration

#1476 Update __repr__ method of major objects in openPMD hierarchy
  include/openPMD/backend/Attributable.hpp
  src/backend/Attributable.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/Container.cpp
  src/binding/python/Dataset.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticlePatches.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/PatchRecordComponent.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
Labels: bug, frontend: Python3, api: new

#1473 Better handling for file extensions
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/Series.cpp
  test/CoreTest.cpp
Labels: cosmetic

#1482 Follow-up to #1470
  src/backend/PatchRecordComponent.cpp
Labels: bug, internal

#1364 HDF5IOHandler: Support for float128 on ARM64/PPC64
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
Labels: backend: HDF5
