Repository openPMD/openPMD-api, pull requests merged in 2023-02, with the labels that each got.

#1369 Iteration.time and Iteration.dt: Prefer double in Python setters
  src/binding/python/Iteration.cpp
Labels: frontend: Python3

#1373 LoadChunk: Better Error Message (Type)
  include/openPMD/RecordComponent.tpp
  test/CoreTest.cpp
Labels: internal

#1370 Pre-Commit: Smaller Files & NB
  .pre-commit-config.yaml
Labels: continuous integration

#1291 New Access type READ_LINEAR
  docs/source/dev/design.rst
  docs/source/usage/streaming.rst
  docs/source/usage/workflow.rst
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/CommonADIOS1IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/Access.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/Iteration.hpp
  include/openPMD/ReadIterations.hpp
  include/openPMD/Series.hpp
  include/openPMD/backend/ParsePreference.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS1IOHandler.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/ADIOS/ParallelADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/ReadIterations.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/backend/PatchRecordComponent.cpp
  src/backend/Writable.cpp
  src/binding/python/Access.cpp
  src/binding/python/openpmd_api/pipe/__main__.py
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, frontend: C++17, frontend: Python3, internal

#1368 Deactivate warning when opening single file of file-based Series
  src/Series.cpp
Labels: warning, cosmetic

#1371 Update examples
  examples/10_streaming_read.cpp
  examples/10_streaming_read.py
  examples/10_streaming_write.cpp
  examples/10_streaming_write.py
  examples/11_particle_dataframe.py
  examples/12_span_write.cpp
  examples/12_span_write.py
  examples/13_write_dynamic_configuration.cpp
  examples/13_write_dynamic_configuration.py
  examples/1_structure.cpp
  examples/2_read_serial.cpp
  examples/2_read_serial.py
  examples/2a_read_thetaMode_serial.cpp
  examples/2a_read_thetaMode_serial.py
  examples/3_write_serial.cpp
  examples/3_write_serial.py
  examples/3a_write_thetaMode_serial.cpp
  examples/3a_write_thetaMode_serial.py
  examples/3b_write_resizable_particles.cpp
  examples/3b_write_resizable_particles.py
  examples/4_read_parallel.cpp
  examples/4_read_parallel.py
  examples/5_write_parallel.cpp
  examples/5_write_parallel.py
  examples/6_dump_filebased_series.cpp
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  examples/9_particle_write_serial.py
  include/openPMD/WriteIterations.hpp
  src/Series.cpp
  src/WriteIterations.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/Container.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Series.cpp
Labels: bug, tests, affects latest release, documentation, frontend: Python3

#1294 Add unique_ptr overloads for storeChunk calls
  examples/12_span_write.cpp
  include/openPMD/Datatype.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/ADIOS/CommonADIOS1IOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/RecordComponent.tpp
  include/openPMD/auxiliary/Memory.hpp
  include/openPMD/auxiliary/TypeTraits.hpp
  include/openPMD/auxiliary/UniquePtr.hpp
  include/openPMD/backend/PatchRecordComponent.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/ADIOS/CommonADIOS1IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/RecordComponent.cpp
  test/CoreTest.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2, api: new
