Repository openPMD/openPMD-api, pull requests merged in 2023-11, with the labels that each got.

#1552 Fix `unique_ptr<T, Del>` constructor of UniquePtrWithLambda
  include/openPMD/auxiliary/UniquePtr.hpp
  test/SerialIOTest.cpp
Labels: bug, affects latest release, frontend: C++17

#1549 Doc: Python 3.12
  Dockerfile
  README.md
  docs/source/dev/dependencies.rst
  setup.py
  share/openPMD/thirdParty/pybind11/tools/pybind11Tools.cmake
Labels: documentation, frontend: Python3

#1545 Fix Attribute copy/move constructors
  include/openPMD/DatatypeMacros.hpp
  include/openPMD/UndefDatatypeMacros.hpp
  include/openPMD/backend/Attribute.hpp
  test/CoreTest.cpp
Labels: bug, affects latest release, frontend: C++17

#1555 Doc: HELPMI Support
  README.md
  docs/source/index.rst
Labels: documentation

#1558 Update cmake minimum required
  share/openPMD/cmake/FindADIOS.cmake
  share/openPMD/thirdParty/json/CMakeLists.txt
  share/openPMD/thirdParty/toml11/CMakeLists.txt
Labels: install
