Repository openPMD/openPMD-api, pull requests merged in 2024-10, with the labels that each got.

#1673 CMake Tar: TOML11 3.7.1
  cmake/dependencies/toml11.cmake
Labels: bug, third party, backend: TOML

#1672 CI: Fix Conda
  .github/workflows/codeql.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/nvidia.yml
  .github/workflows/source.yml
  .github/workflows/tooling.yml
  .github/workflows/windows.yml
Labels: bug, continuous integration

#1675 Python 3.13, pybind11 2.13.0+
  CHANGELOG.rst
  Dockerfile
  NEWS.rst
  README.md
  cmake/dependencies/pybind11.cmake
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  setup.py
Labels: install, frontend: Python3

#1674 ADIOS2 Access Mode: Fix Dangling Ref
  include/openPMD/auxiliary/JSON_internal.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/auxiliary/JSON.cpp
Labels: bug, warning, backend: ADIOS2

#1648 Release notes: 0.16
  CHANGELOG.rst
  NEWS.rst
  README.md
  docs/source/dev/linking.rst
  include/openPMD/version.hpp
Labels: documentation

#1554 Wheels: ADIOS2 v2.10.1
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: backend: ADIOS2, frontend: Python3, continuous deployment

#1678 Fix: CMake Internal Control
  cmake/dependencies/catch.cmake
  cmake/dependencies/json.cmake
  cmake/dependencies/pybind11.cmake
  cmake/dependencies/toml11.cmake
Labels: bug, affects latest release, install

#1679 Revert "CMake Tar: TOML11 3.7.1 (#1673)"
  cmake/dependencies/toml11.cmake
Labels: dependencies

#1681 Replace deprecated makeSuite with loadTestsFromTestCase
  test/python/unittest/Test.py
Labels: tests, affects latest release, frontend: Python3

#1677 Wheels: 0.16.0
  .github/workflows/build.yml
  .travis.yml
Labels: continuous deployment

#1682 Doc: Fix Shipped Internally
  README.md
  docs/source/dev/dependencies.rst
Labels: bug, documentation

#1684 `PYBIND11_FINDPYTHON=ON`
  cmake/dependencies/pybind11.cmake
  setup.py
Labels: bug, affects latest release, install, frontend: Python3

#1690 Fix icx CI run
  include/openPMD/backend/Container.hpp
Labels: bug, continuous integration

#1689 Version 0.17.0-dev
  .github/workflows/windows.yml
  CITATION.cff
  CMakeLists.txt
  README.md
  docs/source/conf.py
  docs/source/dev/linking.rst
  docs/source/index.rst
  include/openPMD/version.hpp
  new_version.py
  setup.py
  test/SerialIOTest.cpp
Labels: install, documentation

#1551 Add openPMD version 2.0 to supported API versions
  include/openPMD/Error.hpp
  include/openPMD/version.hpp
  src/Error.cpp
  src/Series.cpp
  src/binding/python/Error.cpp
  src/version.cpp
  test/CoreTest.cpp
  test/SerialIOTest.cpp
Labels: discussion, api: new

#1691 Add OPENPMD_PYTHON_TEST_PREFIX environment variable
  test/python/unittest/Test.py
Labels: tests

#1683 Fix Leftover ADIOS1 Mentions
  docs/Doxyfile
  docs/source/maintenance/release_channels.rst
  examples/13_write_dynamic_configuration.cpp
  examples/13_write_dynamic_configuration.py
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
Labels: bug, affects latest release, documentation, backend: ADIOS1

#1654 Pickle API: Cache unpickled Series to avoid repeated file access
  include/openPMD/binding/python/Pickle.hpp
  test/SerialIOTest.cpp
Labels: frontend: Python3
