Repository openPMD/openPMD-api, pull requests merged in 2024-07, with the labels that each got.

#1642 Performance: Flush IOHandler only once, not for each Iteration
  include/openPMD/IO/AbstractIOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecord.hpp
  src/IO/ADIOS/ADIOS2File.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandlerImpl.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticlePatches.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/Series.cpp
  src/auxiliary/JSON.cpp
  src/backend/Attributable.cpp
  src/backend/PatchRecord.cpp
  test/SerialIOTest.cpp
Labels: internal

#1632 Flush target newstep
  docs/source/details/backendconfig.rst
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/macros.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  src/IO/ADIOS/ADIOS2Auxiliary.cpp
  src/IO/ADIOS/ADIOS2File.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/Series.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2

#1649 Add missing openPMD_HAVE_MPI guard to ParallelIOTest
  test/ParallelIOTest.cpp
Labels: bug, tests

#1651 Fix Conda CI
  .github/workflows/linux.yml
Labels: warning, continuous integration

#1650 Parse lazily in linear access mode
  src/Series.cpp
Labels: internal

#1645 Compatibility with toml11 4.0
  .github/workflows/linux.yml
  CMakeLists.txt
  include/openPMD/auxiliary/JSON_internal.hpp
  src/IO/ADIOS/ADIOS2File.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/IO/IOTask.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/auxiliary/JSON.cpp
  test/JSONTest.cpp
Labels: third party, internal, backend: TOML

#1653 CI: macOS 11->12
  .github/workflows/macos.yml
Labels: continuous integration

#1633 Pickle API: Avoid static Series hack, allow multiple Series
  include/openPMD/Iteration.hpp
  include/openPMD/ParticleSpecies.hpp
  include/openPMD/RecordComponent.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/BaseRecord.hpp
  include/openPMD/binding/python/Pickle.hpp
  src/backend/Attributable.cpp
  src/binding/python/Iteration.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
  src/binding/python/Series.cpp
  test/python/unittest/API/APITest.py
Labels: frontend: Python3

#1638 ADIOS2: Override access mode
  docs/source/details/backendconfig.rst
  docs/source/usage/workflow.rst
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: backend: ADIOS2
