Repository openPMD/openPMD-api, pull requests merged in 2024-08, with the labels that each got.

#1657 Fix used after free issue in SerialIOTests
  test/SerialIOTest.cpp
Labels: bug, tests

#1522 setup.py: Transitive ZLIB Static
  docs/source/dev/buildoptions.rst
  setup.py
Labels: install, backend: HDF5, backend: ADIOS1, backend: ADIOS2, frontend: Python3

#1634 HDF5 independent flush config
  docs/source/backends/hdf5.rst
  docs/source/details/backendconfig.rst
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandlerImpl.hpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  test/ParallelIOTest.cpp
Labels: backend: HDF5, MPI

#1652 Opt-in support for unknown ADIOS2 engines
  docs/source/backends/adios2.rst
  docs/source/details/backendconfig.rst
  include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp
  include/openPMD/IO/ADIOS/ADIOS2File.hpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  src/IO/ADIOS/ADIOS2File.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
Labels: backend: ADIOS2

#1506 Python: Series to DataFrame
  docs/source/analysis/pandas.rst
  docs/source/analysis/rapids.rst
  examples/11_particle_dataframe.py
  src/binding/python/openpmd_api/DataFrame.py
  src/binding/python/openpmd_api/__init__.py
Labels: third party, frontend: Python3

#1662 Pickle API: Fix memory leak
  src/binding/python/Iteration.cpp
  src/binding/python/Mesh.cpp
  src/binding/python/MeshRecordComponent.cpp
  src/binding/python/ParticleSpecies.cpp
  src/binding/python/Record.cpp
  src/binding/python/RecordComponent.cpp
Labels: bug, frontend: Python3
