Repository openPMD/openPMD-api, pull requests merged in 2024-09, with the labels that each got.

#1583 Replace internal dependencies by FetchContent
  .gitignore
  CMakeLists.txt
  NEWS.rst
  README.md
  docs/source/dev/buildoptions.rst
  docs/source/dev/dependencies.rst
  pyproject.toml
  setup.py
Labels: install

#1667 CMake Superbuild: Repo & Local Source
  CMakeLists.txt
  cmake/dependencies/catch.cmake
  cmake/dependencies/json.cmake
  cmake/dependencies/pybind11.cmake
  cmake/dependencies/toml11.cmake
  docs/source/dev/buildoptions.rst
Labels: install, third party, dependencies

#1659 Python Series/Iteration: Fix Length
  NEWS.rst
  include/openPMD/binding/python/Container.H
  src/binding/python/Attributable.cpp
  src/binding/python/Series.cpp
Labels: bug, affects latest release, frontend: Python3

#1669 Allow numpy 2.0 in requirements.txt
  requirements.txt
Labels: frontend: Python3

#1660 Independent writes: Make workaround more flexible
  include/openPMD/Iteration.hpp
  include/openPMD/RecordComponent.tpp
  include/openPMD/Series.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Writable.hpp
  src/backend/Attributable.cpp
  src/backend/Writable.cpp
  src/binding/python/Attributable.cpp
  test/ParallelIOTest.cpp
Labels: api: new, workaround

#1668 CMake Superbuild: Tarball
  CMakeLists.txt
  cmake/dependencies/catch.cmake
  cmake/dependencies/json.cmake
  cmake/dependencies/pybind11.cmake
  cmake/dependencies/toml11.cmake
  docs/source/dev/buildoptions.rst
Labels: install, third party, dependencies

#1467 Script: New Version
  docs/source/index.rst
  docs/source/maintenance/release_channels.rst
  docs/source/maintenance/release_github.rst
  new_version.py
Labels: tools, documentation
