Repository openPMD/openPMD-api, pull requests merged in 2025-09, with the labels that each got.

#1778 storeChunk: use const-type pointers
  include/openPMD/RecordComponent.hpp
  include/openPMD/auxiliary/ShareRawInternal.hpp
  src/RecordComponent.cpp
Labels: frontend: C++17

#1780 Doc: First Write `np.float64`
  docs/source/usage/firstwrite.rst
Labels: bug, affects latest release, documentation

#1784 Remove leftover from debugging
  src/snapshots/ContainerImpls.cpp
Labels: cosmetic

#1741 Performance optimizations for interacting with many meshes / species types
  include/openPMD/RecordComponent.tpp
  include/openPMD/Span.hpp
  src/Iteration.cpp
  src/Mesh.cpp
  src/ParticleSpecies.cpp
  src/Record.cpp
  src/RecordComponent.cpp
  src/backend/BaseRecord.cpp
  src/backend/MeshRecordComponent.cpp
  src/backend/PatchRecord.cpp
Labels: internal
