Repository openPMD/openPMD-api, pull requests merged in 2025-01, with the labels that each got.

#1710 Example 12: Use ULONG for particle patches
  examples/12_span_write.cpp
Labels: bug, affects latest release

#1676 Release: 0.16.1
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/mpirun_workaround.sh
  .github/workflows/windows.yml
  CHANGELOG.rst
  CITATION.cff
  CMakeLists.txt
  README.md
  cmake/dependencies/catch.cmake
  cmake/dependencies/json.cmake
  cmake/dependencies/pybind11.cmake
  cmake/dependencies/toml11.cmake
  docs/Doxyfile
  docs/source/conf.py
  docs/source/dev/dependencies.rst
  docs/source/dev/linking.rst
  docs/source/index.rst
  docs/source/maintenance/release_channels.rst
  examples/12_span_write.cpp
  examples/13_write_dynamic_configuration.cpp
  examples/13_write_dynamic_configuration.py
  examples/7_extended_write_serial.cpp
  examples/7_extended_write_serial.py
  include/openPMD/backend/Container.hpp
  include/openPMD/version.hpp
  new_version.py
  openPMDConfig.cmake.in
  setup.py
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  test/SerialIOTest.cpp
  test/python/unittest/Test.py
Labels: documentation

#1712 Wheels: 0.16.1
  .github/workflows/build.yml
  .travis.yml
  library_builders.bat
  library_builders.sh
Labels: continuous deployment

#1715 RTD: Sphinx Key
  .readthedocs.yml
Labels: third party, documentation
