Repository openPMD/openPMD-api, pull requests merged in 2025-03, with the labels that each got.

#1726 Backport CI fixes to release 0.16.2
  .github/workflows/source.yml
  .pre-commit-config.yaml
  .readthedocs.yml
Labels: continuous integration

#1728 Further workaround for #1655: Avoid hangup automatically when using writeIterations()
  CMakeLists.txt
  src/Series.cpp
  test/Files_ParallelIO/ParallelIOTests.hpp
  test/Files_ParallelIO/bug_1655_bp5_writer_hangup.cpp
  test/ParallelIOTest.cpp
Labels: bug, affects latest release, workaround

#1729 Backport bugfix 1728 to release branch 0.16.2 (Avoid hangup automatically when using writeIterations())
  include/openPMD/ReadIterations.hpp
  include/openPMD/WriteIterations.hpp
  src/Series.cpp
  src/WriteIterations.cpp
  test/ParallelIOTest.cpp
Labels: bug, affects latest release, backend: ADIOS2, workaround

#1730 Followup: Bug fixes for random-access in variable encoding
  include/openPMD/IO/ADIOS/ADIOS2File.hpp
  src/IO/ADIOS/ADIOS2File.cpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  test/SerialIOTest.cpp
Labels: bug, backend: ADIOS2

#1732 BP5+groupbased: allow only up to 100 steps
  docs/source/backends/adios2.rst
  include/openPMD/IO/ADIOS/ADIOS2File.hpp
  src/IO/ADIOS/ADIOS2File.cpp
Labels: backend: ADIOS2, workaround

#1722 Add compile-time check for issue 1720 (Cuda < 12.4.0 + C++20 + std::variant)
  include/openPMD/openPMD.hpp
Labels: bug, wontfix

#1733 WarpX: Repo Moved
  docs/source/analysis/paraview.rst
Labels: documentation

#1731 CI: Move Ubuntu 20.04 workflows to 22.04
  .clang-tidy
  .github/ci/spack-envs/clang11_nopy_nompi_h5_libcpp/spack.yaml
  .github/ci/spack-envs/clang11_nopy_ompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/clang11_nopy_ompi_h5_ad2_libcpp/spack.yaml
  .github/ci/spack-envs/clang15_py311_nompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/clangtidy_nopy_ompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/gcc12_py36_ompi_h5_ad2/spack.yaml
  .github/ci/spack-envs/gcc13_py312_mpich_h5_ad2/spack.yaml
  .github/workflows/dependencies/install_nvcc12.sh
  .github/workflows/dependencies/install_nvhpc25-1.sh
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/nvidia.yml
  .github/workflows/tooling.yml
  examples/3a_write_thetaMode_serial.cpp
  examples/5_write_parallel.cpp
  examples/8_benchmark_parallel.cpp
  examples/8b_benchmark_read_parallel.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  test/Files_ParallelIO/bug_1655_bp5_writer_hangup.cpp
  test/ParallelIOTest.cpp
  test/SerialIOTest.cpp
Labels: continuous integration

#1738 Fix zero-sized storeChunk for Span API in Python
  src/binding/python/RecordComponent.cpp
Labels: bug, frontend: Python3

#1739 Reactivate MPICH runner (gcc13_py312_mpich_h5_ad2)
  .github/ci/spack-envs/gcc13_py312_mpich_h5_ad2/spack.yaml
  .github/workflows/dependencies/install_mpich
  .github/workflows/linux.yml
Labels: continuous integration, workaround

#1646 Dataset-specific JSON/TOML configuration
  CMakeLists.txt
  docs/source/details/backendconfig.rst
  docs/source/details/openpmd_extended_config.json
  docs/source/details/openpmd_extended_config.toml
  examples/13_write_dynamic_configuration.cpp
  include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp
  include/openPMD/IO/AbstractIOHandler.hpp
  include/openPMD/IO/AbstractIOHandlerHelper.hpp
  include/openPMD/IO/HDF5/HDF5IOHandler.hpp
  include/openPMD/IO/HDF5/HDF5IOHandlerImpl.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandler.hpp
  include/openPMD/IO/HDF5/ParallelHDF5IOHandlerImpl.hpp
  include/openPMD/IO/IOTask.hpp
  include/openPMD/IO/JSON/JSONIOHandler.hpp
  include/openPMD/IO/JSON/JSONIOHandlerImpl.hpp
  include/openPMD/auxiliary/JSON.hpp
  include/openPMD/auxiliary/JSONMatcher.hpp
  include/openPMD/auxiliary/JSON_internal.hpp
  include/openPMD/backend/Attributable.hpp
  include/openPMD/backend/Writable.hpp
  src/IO/ADIOS/ADIOS2IOHandler.cpp
  src/IO/AbstractIOHandler.cpp
  src/IO/AbstractIOHandlerHelper.cpp
  src/IO/DummyIOHandler.cpp
  src/IO/HDF5/HDF5IOHandler.cpp
  src/IO/HDF5/ParallelHDF5IOHandler.cpp
  src/IO/IOTask.cpp
  src/IO/JSON/JSONIOHandler.cpp
  src/IO/JSON/JSONIOHandlerImpl.cpp
  src/Series.cpp
  src/auxiliary/JSON.cpp
  src/auxiliary/JSONMatcher.cpp
  src/backend/Attributable.cpp
  src/binding/python/Attributable.cpp
  src/binding/python/Series.cpp
  test/AuxiliaryTest.cpp
  test/CoreTest.cpp
  test/JSONTest.cpp
  test/ParallelIOTest.cpp
Labels: api: new
